### ISSUE TITLE
npm run deploy (or similar) to create a proper version

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#112]
Every deployment/release must:
- Have an unique version number. Counting up patch number seems fine to me.
- Have this version number as a git-tag (again: having a lot of git tags is not too bad)
- Have this same version as npm version

Here is some inspiration from melon.js: https://github.com/melonproject/melon.js/blob/master/package.json#L29 (also check "version" and "postversion" commands)

--> It should be super trivial to find the corresponding protocol source to a version on npm.
Now it's almost impossible :(

**Comment by retotrinkler** [comment]
Similar to #67

**Comment by retotrinkler** [comment]
Similar to #49

**Comment by retotrinkler** [comment]
- [ ] option for versions eg for foundation, kovan, stagin etc deployments
- [ ] stores output - eg abi, address, network in config file - see #67

**Comment by travs** [comment]
To my knowledge, we now do something like this (correct/amend please):
```sh
# with open node running in bg
git checkout develop
rm -rf build/
npm test  # passes
npm run deploy
npm version 0.3.2-alpha.5  # or whatever version number
npm publish
git push && git push --follow-tags
```

Need to make the changes Reto mentioned above, so we're not there yet, but this is a start
