### ISSUE TITLE
Add return values to user-critical functions

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#125]
This is to allow basic preflight calls for error-checking (e.g. correct gas amount).
Could just return a boolean or we can get more fancy with error codes

- [ ] version.setupVault()

**Comment by schmidsi** [comment]
I'm happy with booleans. I don't see how you can return from pre_conditions anyways.

**Comment by retotrinkler** [comment]
Have started this: eg https://github.com/melonproject/protocol/blob/master/contracts/Fund.sol#L515-L523
As of now it logs which `pre conditions` to 'actual' function body fails when an actual tx gets sent. (Basic draft - assumed to change a lot still)

For next release was thinking of an [error first callback](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/) style. This would return whether and which `pre conditions` fails even in context of read-only call. Would prob fit in nicely w concept of pre-flight calls.

**Comment by schmidsi** [comment]
Awesome. What would be the cost of logging strings instead of numbers. I.e. "MAKE_NOT_PERMITTED" instead of 1. Would make debugging a bit easier.

And is it better security/gas wise to have modifiers instead of in-function code?

Note sure about the error-first callback style. As far as I understand solidity, functions are not first-class objects so they cannot be passed as an argument to another function. And that is what error-first callback style is all about.

**Comment by retotrinkler** [comment]
> What would be the cost of logging strings instead of numbers. I.e. "MAKE_NOT_PERMITTED" instead of 1. Would make debugging a bit easier.

makes sense! additional costs would only incur when pre conditions fail - which should be fairly rare. For pre flight calls its free

> And is it better security/gas wise to have modifiers instead of in-function code?

Think its same

> functions are not first-class objects so they cannot be passed as an argument to another function. 

was thinking something along the lines of

```
const (err, res) = await fundContract.makeOrder(order.details).call(); // Pre-flight; Read only call, is free for user
if (err) {
    ... // Error handling, notifing user of eg err == MAKE_NOT_PERMITTED
} else { 
    txReceipt = await fundContract.makeOrder(order.details); // Now that we know pre-flight is passing we send actual tx
}
```

**Comment by schmidsi** [comment]
This:

```javascript
// slightly changed to array-deconstruction
const [err, res] = await fundContract.makeOrder().call(order.details);
```

works and I like it. I think this pattern is called railways and comes from the functional-programming land. Some slides about this topic that describe the concept can be found [here](http://fsharpforfunandprofit.com/rop/) if anybody is interested to go deeper in this topic.

**Comment by retotrinkler** [comment]
nice thanks

**Comment by retotrinkler** [comment]
```javascript
const (err, errMsg) = await fundContract.makeOrder(order.details).call(); // Pre-flight; Read only call, is free
if (err) {
    ... // Error handling, notifing user of eg errMsg == MAKE_NOT_PERMITTED
} else { 
    txReceipt = await fundContract.makeOrder(order.details); // Now that we know pre-flight is passing we 
send actual tx
}
```
