### ISSUE TITLE
Fix: EtherToken as Premined Asset

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#131]
_ethertoken can be emptied; an ethertoken usually means you can convert between ether and ethertokens without problems. However, since this is a 'PreminedAsset', it means that it can have a larger 'debt' than balance, and thus won't have the invariant that tokens can be exchanged for ether at all times._

**Comment by retotrinkler** [comment]
non-issue for live deployment

**Comment by travs** [comment]
Redundant after #239 complete
