### ISSUE TITLE
Trade event timestamp

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#134]
Would it be possible to have a timestamp on trade events? 

https://github.com/melonproject/protocol/blob/develop/contracts/exchange/SimpleMarket.sol#L8

**Comment by retotrinkler** [comment]
its difficult there as this is going to be third party software (DappHub)
there is a order timestamp in vault https://github.com/melonproject/protocol/blob/develop/contracts/Vault.sol#L88
does this sufficient for a workaround?

**Comment by jennazenk** [comment]
The event in Vault would give us the time when the order was placed I believe. I thought for trade history would be good to know when trade was fully executed. We used to do it server side in the previous portal by storing in Trades collection all trades coming i w a timestamp, but can't do it on d-portal. Not urgent at the moment, will look if possible to find another workaround.
