### ISSUE TITLE
OfferUpdate

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#135]
Would it be possible to fire an OfferUpdate event in the make function (https://github.com/melonproject/protocol/blob/develop/contracts/exchange/SimpleMarket.sol#L135) as per : https://github.com/melonproject/protocol/blob/v0.1.2-deploy.2/contracts/exchange/Exchange.sol#L94

**Comment by retotrinkler** [comment]
Yes this should be possible using an `ExchangeAdapter` contract which inherits from `SimpleMarket`

**Comment by retotrinkler** [comment]
same methodology should apply for Trade event mentioned in https://github.com/melonproject/protocol/issues/134

let me have a look and see what I can do :)

**Comment by retotrinkler** [comment]
it would restrict the set of Trade and UpdateOrder events to events triggered by Melon funds - but should be sufficient for our purposes

**Comment by jennazenk** [comment]
Cool 👍 ! Would be great
