### ISSUE TITLE
Brainstorm: Deployment-wide event watch with contract independent filters

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#137]
**The ultimate goal** is to have only one watch open from each client which triggers for every relevant event.

According to the [JSON-RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter) we can filter for two “fields”: 
- Contract address(es)
- Topic(s) (= indexed event argument, whereas the first topic is always SHA3 of the signature of the filter something like `sha3("Deposit(address,bytes32,uint256)")`)

It is not clearly stated, but I assume that these two fields are ANDed together. Meaning if we specify an address AND a topic, the filter will trigger only for events on that address that match that topic.

That leads to 3 general strategies:

# Strategies

## Collect all relevant addresses and filter for those
This is the most obvious approach. The only question is: Do we know all addresses by triggering the filter? I think yes for a single vault, but no for the version because new vaults can be added all the time.

Pro: Verified event origins
Con: Hard to keep up with all relevant addresses

## Collect all signatures of relevant events and filter for those
This also seems a good idea but has one big drawback: Everyone could trigger an event like this and this will trigger our watch function, by coincidence or maliciously. In order to mitigate this risk, we need to check in the watch function if the event is legitimate.

Pro: Independent of contract addresses
Con: No control over event origin --> Further checks needed

## Introduce a special topic (i.e. event argument)
A derived strategy from collecting all signatures is the introduction of a deployment-wide argument, that every event trigger has in it. Something like: `MyEvent(bytes32 appId)` called with `MyEvent('melon@0.3.8')`.
This defends from coincidentally triggered events from other contracts but not from an malicious attacker. So we still need to check for legitimacy.

Pro: Like above + prevents coincidentally wrong events + shorter filter query
Con: Still needs checks

Checks means: We need to verify the data from the event with a second call. This is not super bad, but a bit ugly. That also means: There is no need to send a lot of information with the event itself because we need to query the blockchain again anyways.

# Conclusion
I think the best strategy is working with "Collect all relevant addresses". It gives us security over the origin of the events and with this we can add all relevant information to the event which gives a slight performance advantage and cleaner code on both sides.

The problem with the changing addresses could be solved by stopping, reconfiguring and restarting the filter watch for every change. Furthermore, for single-vault applications like the current decentralised portal, there aren't any address changes after the vault is setup as far as I know?

**Comment by jennazenk** [comment]
"The problem with the changing addresses could be solved by stopping, reconfiguring and restarting the filter watch for every change. Furthermore, for single-vault applications like the current decentralised portal, there aren't any address changes after the vault is setup as far as I know?"

Correct, for the current decentralized portal there would be no address changes after the vault is setup. This problem would arise if we wanted to implement the vaults ranking on the decentralized-portal (ie w no server to keep track of vaults addresses)

**Comment by schmidsi** [comment]
"Collect all relevant addresses".

First experiments are done here: https://github.com/melonproject/melon.js/tree/global-watc
