### ISSUE TITLE
MLN tokens transferred to vault address before subscribe request is executed.

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#139]
MLN tokens are transferred to the vault address in the subscribe function: 
https://github.com/melonproject/protocol/blob/develop/contracts/Vault.sol#L462

Does it mean that MLN tokens are available for the fund to trade even before the subscribe request got executed (executeRequest), ie. even before the shares were created?

**Comment by retotrinkler** [comment]
they are held in look up but a `cancelRequest` function can be called to release them again from look up

**Comment by retotrinkler** [comment]
https://github.com/melonproject/protocol/blob/develop/contracts/Vault.sol#L562
