### ISSUE TITLE
Register assets in DataFeed contract

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#144]
Would be great for next npm alpha release that: 

(i) all assets get registered in the data feed (right now, none of them are, and I think they should since the datafeed now acts as the universe.
(ii) Maybe the ```update``` function on the DataFeed contract should check if the asset is registered before updating the price (https://github.com/melonproject/protocol/blob/0.3.2-alpha.14/contracts/datafeeds/DataFeed.sol#L183)

 J 👩🏽‍💻

**Comment by retotrinkler** [comment]
@travs can u include this in new deployment script

**Comment by retotrinkler** [comment]
ah right reason for no `pre_cond(isRegistered(ofAsset))` was to try to keep the gas costs down as this would need to be checked for all the assets of the assets array and for each call to the `update(..)` function

**Comment by jennazenk** [comment]
Alright I see! Well just having them registered in the datafeed would already be great :)

**Comment by travs** [comment]
@retotrinkler absolutely - will be included

**Comment by retotrinkler** [comment]
is done
