### ISSUE TITLE
High Water Mark for Performance Fee

### ISSUE THREAD

**Issue by agedubbs** [melonproject/protocol#212]
**Definition:** 

The High Water Mark (HWM) is the highest peak of the net asset value per share (NAV/share) that an investment fund has reached. The HWM protects the investor by ensuring that the portfolio manager does not get paid for poor performance as well. If the PM loses money over a period, he must get the fund above the HWM first before receiving performance fees again. This also ensures that the investor does not have to pay twice for the same performance.

**Example**:

Hansen is a portfolio manager. He charges 2% management fee and 20% performance fee. His fund is incepted today (year 0) with a NAV/share of 100 MLN . For simplicity, he only has one investor --> Tom.

In year 1, the fund's NAV/share goes from 100 MLN to 120 MLN. Hansen receives 20% of the performance: 4 MLN.

In year 2, the NAV/share of Hansen's fund drops from 120 to 80. He does not receive performance fees this year, since his performance was -33.33%.

In year 3, Hansen's fund goes back up from 80 MLN/share to 100 MLN/share. Without a HWM, Hansen should receive a performance fee of 4 MLN this year again. Here you see the importance of a HWM very clearly: Tom paid a performance fee of 4 MLNs twice (total 8 MLN), though the value of his investments did not change (he started with 100 MLN per share and ended up with 100 MLN per share).

Will upload first proposal of HWM soon.

**Comment by jennazenk** [comment]
Duplicate #193

**Comment by agedubbs** [comment]
just saw, thanks!
