### ISSUE TITLE
Error when running "npm run compile"

### ISSUE THREAD

**Issue by pier-rosini** [melonproject/protocol#224]
On npm run compile I get the the following error in the console

 export SOLC_FLAGS='--optimize' && make all

'export' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @melonproject/protocol@0.4.1 compile: `export SOLC_FLAGS='--optimize' && make all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @melonproject/protocol@0.4.1 compile script 'export SOLC_FLAGS='--optimize' && make all'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @melonproject/protocol package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     export SOLC_FLAGS='--optimize' && make all
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @melonproject/protocol
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @melonproject/protocol
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pier\IdeaProjects\test\npm-debug.log
[npm-debug.log](https://github.com/melonproject/protocol/files/1500147/npm-debug.log)

**Comment by GauthamN** [comment]
Hi, thanks for taking your time to report the issue. Since you are using Windows, please replace 'export' keyword with 'set' in package.json and try.

**Comment by pier-rosini** [comment]
HI,
I have done that, but I still get a similar issue:

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program
Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @melonproject/protocol@0.4.0-live.2 compile: `set
SOLC_FLAGS='--optimize' && make all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @melonproject/protocol@0.4.0-live.2 compile script
'set SOLC_FLAGS='--optimize' && make all'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the
@melonproject/protocol package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     set SOLC_FLAGS='--optimize' && make all
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs @melonproject/protocol
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @melonproject/protocol
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pier\IdeaProjects\protocol-master\npm-debug.log

On Fri, Nov 24, 2017 at 11:17 AM, Gautham Nekkanti <notifications@github.com

**Comment by travs** [comment]
I think you will eventually have to update Node to `>=8.0.0`, and NPM as well (latest if possible), though it may not solve this exact problem.

Which shell are you running this in (`cmd.exe`, powershell, babun, etc)?
And please confirm that you have the `make` command available by running `where make` or similar (some other options may be [here](https://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line) if `where` doesn't work).

Also, if you are willing to do so, installing the [windows subsystem for linux](https://msdn.microsoft.com/en-us/commandline/wsl/install-win10?f=255&MSPPError=-2147217396) would probably allow this to run out of the box, but that's entirely up to you :)

**Comment by GauthamN** [comment]
Also try running dapp build command and see if it works. (Assuming you completed the dapp tools installation step)

**Comment by pier-rosini** [comment]
Hi,
Now, I am trying on mac, and I have an issue related to dapp.

I get the following error on console

> @melonproject/protocol@0.4.1 compile
/Users/pierfrancescorosini/IdeaProjects/protocol

> export SOLC_FLAGS='--optimize' && make all


dapp build

dapp-remappings: error: ./lib/ds-test is not a Git repository

dapp-remappings: error: try "dapp update" to initialize submodules

make: *** [all] Error 1

npm ERR! code ELIFECYCLE

npm ERR! errno 2

npm ERR! @melonproject/protocol@0.4.1 compile: `export
SOLC_FLAGS='--optimize' && make all`

npm ERR! Exit status 2

npm ERR!

npm ERR! Failed at the @melonproject/protocol@0.4.1 compile script.

npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.


npm ERR! A complete log of this run can be found in:

npm ERR!
/Users/pierfrancescorosini/.npm/_logs/2017-11-25T09_14_17_204Z-debug.log





and when I try dapp update I get


+ git submodule update --init --recursive

fatal: Not a git repository (or any of the parent directories): .git


and dapp build


dapp build

dapp-remappings: error: ./lib/ds-test is not a Git repository

dapp-remappings: error: try "dapp update" to initialize submodules



If I run sudo make link in the dapp folder I get

rm -rf /usr/local/bin/dapp /usr/local/libexec/dapp

mkdir -p /usr/local/{bin,libexec}

for x in bin/dapp libexec/dapp; do \

ln -s `pwd`/$x /usr/local/$x; done

**Comment by pier-rosini** [comment]
Hi, please ignore my last email, I assume something went wrong cloning the
repo.
I have deleted and reimported the project and now it's all good.

Thanks for the support and apologies for spamming.

Best

**Comment by GauthamN** [comment]
Glad that you've solved the problem.
