### ISSUE TITLE
Investigation: setupFund signing process

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#232]
is [that](https://github.com/melonproject/protocol/blob/master/tests/fund-shares.js#L168) a typo and should be `sig.substr(64,128)'

**Comment by GauthamN** [comment]
It's not a typo. I think it's confusing because of str.substr(start[, length]), the second argument is the length instead of the ending character position.

**Comment by retotrinkler** [comment]
ah got it - thx
