### ISSUE TITLE
quantityHeldInCustodyOfExchange returns wrong (Fund.sol)

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#235]
*From audit*

`openMakeOrderId` is not set to nonzero anywhere, so this method will always return 0.

Additionally, the method takes an address `ofAsset` which is totally ignored by the method.

**Comment by retotrinkler** [comment]
@GauthamN think u were right in ur approach https://github.com/melonproject/protocol/tree/audit-g

**Comment by GauthamN** [comment]
Addressed in f4a18bc28d117ec608d44c9d55618858583d540c
