### ISSUE TITLE
convertUnclaimedRewards invariant breach (`Fund.sol`)

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#236]
*From audit*

When converting rewards into shares, there is a break of an invariant.

```
// Convert unclaimed rewards in form of ownerless shares into shares which belong to manager
uint shareQuantity = totalSupply.mul(unclaimedRewards).div(gav);
totalSupply = totalSupply.sub(shareQuantity); // Annihilate ownerless shares
addShares(owner, shareQuantity); // Create shares and allocate them to manager
```

Consider the following example:

* `totalSupply` is `100`, with `10` holders each holding `10` shares
* `shareQuantity` returns `5` shares
* `totalSupply` becomes `95`
* `addShares(owner, 5)` sets `totalSupply` back to 100, and allocates `5` shares to `owner`

The result being: `10` holders with `10` shares each, and `owner` holding `5` shares, totalling `105` shares. However, the `totalSupply` is only `100` shares.

This breaks the invariant that the sum of share-holdings equals the `totalSupply`.

**Recommendations**

Investigate how the underlying model should be modified to ensure that the total supply (credit) is equal to the sum of holdings (debit).

**Comment by retotrinkler** [comment]
should be solved now
