### ISSUE TITLE
Use of 'toggle' type functions (`Fund.sol`)

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#246]
*From audit*

```
function toggleSubscription() external pre_cond(isOwner()) { isSubscribeAllowed = !isSubscribeAllowed; }
function toggleRedemption() external pre_cond(isOwner()) { isRedeemAllowed = !isRedeemAllowed; }
```

Functions to toggle states are dangerous, as they can lead to accidental state
changes, such as in cases where the caller does not check the current state,
accidentally submits a transaction twice, or two callers submit the same transaction.

Instead, we recommend replacing these with functions that take a bool and update
the flag accordingly.

**Comment by GauthamN** [comment]
f4a18bc28d117ec608d44c9d55618858583d540c
