### ISSUE TITLE
Possibly fail-prone price feed (`DataFeed.sol`)

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#250]
*From audit*

The method `update` of a price-feed does not enforce that all assets are updated when `update` is called.

A fund manager may want to update prices in two discrete calls, in order to keep the gas levels low. However, doing so means that the `dataHistory` for the index `LastUpdateId()` : `nextUpdateId - 1` is not set, which will result in the `price` to effectively return `0`.

```
    function getPrice(address ofAsset)
        constant
        pre_cond(isDataSet(ofAsset))
        pre_cond(isDataValid(ofAsset))
        returns (uint dataFeedPrice)
    {
        return dataHistory[getLastUpdateId()][ofAsset].price;
    }
```

**Recommendations**

Ensure that the behaviour of `update` when passed partial data is consistent with expectations.

**Comment by retotrinkler** [comment]
solution suggestion;
- asset specific mappings here https://github.com/melonproject/protocol/blob/master/src/datafeeds/DataFeed.sol#L32-L33

needs to be check whether sensible in context of https://github.com/melonproject/protocol/blob/master/src/Fund.sol#L429-L441

**Comment by retotrinkler** [comment]
think https://github.com/melonproject/protocol/blob/master/src/Fund.sol#L422-L434 these should be asset specific lookups (might get expensive though)

**Comment by travs** [comment]
Closing this as we've removed `dataHistory` from `PriceFeed`
