### ISSUE TITLE
Owned offers no provision for changing ownership (`Owned.sol`)

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#256]
*From audit*

Unlike many implementations of the `Owned` pattern, this implementation provides
no mechanism for changing ownership.

**Recommendations**

We recommend adding one, to cater for situations such as key rotation or the need to migrate to a new multisig wallet.

**Comment by travs** [comment]
At a glance, looks like we may be able to use `ds-group` here

**Comment by GauthamN** [comment]
I think simple owner variable change is enough. Because ds-group would be the concern of another layer as the ds-group contract address can be simply set as owner address

**Comment by GauthamN** [comment]
Addressed in da4e64b01b4fd846f4e580a8590666a419bd00e8
