### ISSUE TITLE
Underuse of modifiers (`Fund.sol`)

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#262]
*From audit*

Many functions, such as `requestSubscription`, `requestRedemption`, `executeRequest` and `cancelRequest` contain checks that could be more succinctly expressed as preconditions.

**Recommendations**

We recommend rewriting these as modifiers or preconditions for clarity.

**Comment by GauthamN** [comment]
Aren't they written that way for error logging purpose?

**Comment by retotrinkler** [comment]
yeah
