### ISSUE TITLE
Unnecessarily exposed methods and confusing naming (`Fund.sol`)

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#264]
*From audit*

`calcGav`, `calcUnclaimedRewards`, `calcNav` and `calcValuePerShare` are internal
methods that are part of the accounting process, and shouldn't be exposed publicly.

`calcUnclaimedRewards` returns `managementReward`, `performanceReward` and
`unclaimedRewards`, but the latter is simply the sum of the first two. If the
individual arguments are required by callers, the third should be omitted, and
callers can add the two values together to obtain it.

`performCalculations` is poorly named, and does not reflect its purpose.

Finally, `calcSharePrice` simply extracts a single element from the `performCalculations`
return tuple, and is redundant.

**Comment by jennazenk** [comment]
We use `calcGav` in Melon.js. If you put it as internal, we can still get it from performCalculation though. It's just that it will perform all the calculations in a case that we would need only GAV.
