### ISSUE TITLE
Orders are never cleaned up (`Fund.sol`)

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#265]
*From audit*

Orders are added to an array as they're placed, but are never deleted to free
storage when they are cancelled or filled. In the interest of being a good
'blockchain citizen', we recommend deleting obsolete data.

**Comment by retotrinkler** [comment]
`    enum OrderStatus { active, partiallyFilled, fullyFilled, cancelled }
` 
we never utilize to `partiallyFilled`
