### ISSUE TITLE
Export abi files with .json file extension

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#293]
To read and process ABI files in JavaScript (frontend), they need to have a .json file extension in order to be universally loadable (i.e. through webpack, rollup, ...).

Can we just add a .json in the end. F.e. Fund.abi.json?

This is a blocker issue for frontend development right now. The only workaround would be to copy/paste/rename the ABI files into melon.js.

**Comment by retotrinkler** [comment]
sounds good.

we could a little js or python script which uses `mv Fund.abi Fund.abi.json` for all files using [sub process](https://nodejs.org/api/child_process.html) and executed before `npm publish` eg as `npm run publish` w

`"publish": "./addJsonEnding && npm publish",
