### ISSUE TITLE
General cleanup

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#300]
- [x] natspec comments
- [x] consistent style accross all contracts
    - function ordering as in http://solidity.readthedocs.io/en/develop/style-guide.html#order-of-functions
- [x] clean concise README 
    - Examples https://github.com/matiassingers/awesome-readme
- [x] https://asciinema.org/
    - Setup
    - Tests
    - HEVM
    - Oyente

**Comment by retotrinkler** [comment]
function ordering as in http://solidity.readthedocs.io/en/develop/style-guide.html#order-of-functions

**Comment by retotrinkler** [comment]
README
- https://asciinema.org/
- https://github.com/matiassingers/awesome-readme

**Comment by travs** [comment]
Just a note: can't get them to compile locally, so updating the doxity docs depends on the result of [this](https://github.com/DigixGlobal/doxity/issues/24) I think

**Comment by retotrinkler** [comment]
nice

**Comment by retotrinkler** [comment]
closing this one
