### ISSUE TITLE
Native Currency and Reference Asset as the only two options to invest/redeem using single asset

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#321]
As discussed think we should move to Native Currency and Reference Asset as the only two options to invest/redeem.

Time sensitive - should be before next audit starts.

**Comment by jennazenk** [comment]
What happens if all investors want to redeem at the same time and fund doesnt have necessary MLN/Referecen Asset?

**Comment by retotrinkler** [comment]
then they need to use the `redeemOwnedAssets` i.e. redeem using slice

**Comment by jennazenk** [comment]
right so redeem with slice will still be an option

**Comment by retotrinkler** [comment]
y

**Comment by GauthamN** [comment]
Closing this as it's already been implemented.
