### ISSUE TITLE
Adding of Tokenfallback in Fund.sol

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#322]
Fund should have **token** fallback - where case is handled of investor sending (=_redeeming_) `shares` directly to the fund ethereum address

Related https://github.com/melonproject/protocol/issues/321
Related https://github.com/melonproject/protocol/issues/323

**Comment by travs** [comment]
This is added now (from 73fa92ccc6c65fc524907d3393700cd4ddf19e09)
