### ISSUE TITLE
Adding of Fallback in Fund.sol

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#323]
Fund should have **native currency** fallback - where case is handled of investor sending (=_subscribing_) `native currency`, e.g ether or melon on melon chain directly to the fund ethereum address

Related https://github.com/melonproject/protocol/issues/321
Related https://github.com/melonproject/protocol/issues/322

**Comment by GauthamN** [comment]
Addressed in b8b170d7d614b0d8a5057857054ee2b8a8091c46
