### ISSUE TITLE
Funds are vulnerable to owning malicious assets

### ISSUE THREAD

**Issue by GauthamN** [melonproject/protocol#331]
From Audit: A fund is exposed to risk that any owned asset is malicious. Any third-party
contract, but especially assets, should be regarded as untrusted code.

**Impact:​ ​**It can become impossible to successfully call any method that iterates over held
Assets: calcGav, redeemOwnedAssets, which affects performCalculations,
calcSharePrice, executeRequest (to buy or sell shares). This effectively freezes the
fund, although shares can still be transferred, as they are valid ERC223 tokens.

**Comment by travs** [comment]
Have begun adding a test for this [here](https://github.com/melonproject/protocol/tree/malicious-asset-test)

**Comment by travs** [comment]
We have a test now, for redeeming when a malicious asset is present, and it passes locally.
When the build passes is this issue considered resolved, or did we want to go further?

**Comment by retotrinkler** [comment]
no think it can be closed now
