### ISSUE TITLE
Funds are exposed to vulnerabilities in modules

### ISSUE THREAD

**Issue by GauthamN** [melonproject/protocol#332]
From Audit: Functionality that is critical to funds are supplied by third-party
modules selected by the fund manager. Any vulnerability in these modules can affect funds using them. Therefore, it is critical that fund owners have the tools they need to make good security decisions.

**Impact**:​ ​Vulnerabilities​ ​in modules can effect fund functionality in various ways. Problems
with risk management or compliance modules is unlikely to have catastrophic effects.
Vulnerabilities in pricefeed or exchange modules could cause unprofitable trades to be
made, or to manipulate the calculated value of the fund. Popular modules are likely to be
high value targets.

**Comment by retotrinkler** [comment]
PriceFeed is trusted entity, staked first and foremost w their reputation, eg Thomson Reuters.
We assume that third party exchanges are independently audited, eg OasisDex, 0x, Kyber

Compliance and riskmgmt are called before they change any state on Fund.sol contract thus there is no explicit danger of re-entrancy.

There are however no guarantees that the code in compliance or riskmgmt is vulnerabilities free for all module builders. Its up to the fund manager and investor to do due diligence. There will be audited versions of compliance and riskmgmt modules from Melonport however
