### ISSUE TITLE
Funds are vulnerable to re-entrance from modules

### ISSUE THREAD

**Issue by GauthamN** [melonproject/protocol#333]
From Audit: Melonport code largely designs to prevent re-entrance from calling contracts.
Calls to modules, however, permit a malicious module to re-enter.

**Impact**:​ ​Module developers may be able to piggyback on users’ transactions and re-enter
the contract. This could allow price feeds to front-run users, and/or manipulate fees.

**Comment by retotrinkler** [comment]
Only modules that change state before they are called are

- `Exchange`
- `PriceFeed`
- `ExchangeAdapter`

Exchanges such as OasisDex, 0x or Kyber that are already on the live net are assumed to be properly audited and for our intends and purposes deemed secure.

PriceFeeds for the time being we are reliant on off-chain price feeds. PriceFeeds are trusted entities w/in the Melon ecosystem and are staked first and foremost w the reputation of the entity providing prices. Eg Thomson Reuters or are CryptoCompare, Oraclize.

ExchangeAdapters should not be more frequently used than the Exchanges itself - One set of  ExchangeAdapters are build by Melonport which makes sure that they are being audited before releasing them.
