### ISSUE TITLE
Use of confusing module names

### ISSUE THREAD

**Issue by GauthamN** [melonproject/protocol#334]
From Audit: Modules can be published with the same or similar names as a phishing attack,
which may induce a fund manager to select a vulnerable or malicious module. Confusing
names can also be used for injection attacks on pages that describe or let managers select
modules.

**Impact:​ ​**Fund managers may be fooled into selecting insecure modules.

**Comment by retotrinkler** [comment]
something we can mitigate to some degree on the frontend
