### ISSUE TITLE
Reputation of module authors

### ISSUE THREAD

**Issue by GauthamN** [melonproject/protocol#335]
From Audit: A different address is used to publish each module, making it difficult to acquire
reputation as a module developer. The lack of a robust identity for module authors lowers
the bar for impersonation attacks.

**Impact:​** ​It is harder for fund managers to know whether they should trust a given module,
which may lead them to using a vulnerable or malicious module.

**Comment by retotrinkler** [comment]
would postpone this for a later version as not crucial at this stage and there are simple methods to link identities across addresses
