### ISSUE TITLE
Error logging for CryptoCompare API calls

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#339]

**Comment by travs** [comment]
If the request itself fails (e.g. no network available), `request-promise` throws an error.
Have just added a sanity check for the prices returned by the API call in 2ac1c32

**Comment by travs** [comment]
also see 91e4dea1d6c139465b73588f343237218c037b46 (retry on bad network)

**Comment by retotrinkler** [comment]
ok super - think can be closed then
