### ISSUE TITLE
Setup multiple funds with same address

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#344]
*Scenario*: John is a well known and serious fund manager. Because of that, he verifies his address with a sybil-resistant verification service. He plans to setup 3 different funds for his different types of investors.

*Problem*: With the current implementation (https://github.com/melonproject/protocol/blob/develop/src/version/Version.sol#L108) it is not possible to setup multiple funds from the same address. But John cannot verify another address because of sybil-attack-resistance of the choosen verification service.

**Comment by retotrinkler** [comment]
we decided to go w one address one fund s.t. if manager shutsdown a fund he can restart one eg w updated pricefeed/compliance/riskmgmt module.

having paradigm of one address one fund will help identify that a fund is being _continued_ w modified settings.

on frontend level, past performance could be visualised and effectively ported over to new fund (w disclaimer that this happened)

this should be of help when it comes to fund-level governance

**Comment by schmidsi** [comment]
Makes sense with the continuation.

So there is no scenario where one KYC-confirmed address manages multiple funds?

**Comment by retotrinkler** [comment]
not as of now

**Comment by schmidsi** [comment]
Thanks for clarification
