### ISSUE TITLE
Prevent secondary trading of shares

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#347]
To make Melon more legally compliant we should consider preventing secondary trading of shares

i.e. here https://github.com/melonproject/protocol/blob/linting/src/assets/Shares.sol#L43
adding something similar to 

```Javascript
function transfer(address _to, uint256 _value) public returns (bool) { require(false); }
function transfer(address _to, uint256 _value, bytes _data) public returns (bool) { require(false); }
function transferFrom(address _from, address _to, uint256 _value) public returns (bool) { require(false); }
```

**Comment by GauthamN** [comment]
This solution means funds of funds functionality cannot be realized?

**Comment by retotrinkler** [comment]
yeah
