### ISSUE TITLE
Renaming referenceAsset -> baseAsset

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#348]
As we changed functionality of referenceAsset from being the currency to mainly used to measure the mgmt/performance fees against _to_ the currency used to invest/redeem directly into the fund. This currency can be seen as the base, cash, stable asset the fund uses

thus would rename referenceAsset to baseAsset

**Comment by GauthamN** [comment]
91a3a72e3eacd8101720e79c0e52aed435cc114b fixes this
