### ISSUE TITLE
Precision issue in calcGav

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#350]
Think this line needs to be multiplied by 1e18 (v0.6.0)

https://github.com/melonproject/protocol/blob/v0.6.0/src/Fund.sol#L507

**Comment by retotrinkler** [comment]
should be fixed w 0.6.2

**Comment by retotrinkler** [comment]
@jennazenk could u detail the inputs and outputs for above err

**Comment by jennazenk** [comment]
Sure, after creating a fund, first call to performCalculations (before investing anything) returns : 

fund.performCalculations raw output: 
````
{ gav: 0,
  managementReward: 0,
  performanceReward: 0,
  unclaimedRewards: 0,
  rewardsShareQuantity: 0,
  nav: 0,
  sharePrice: 1000000000000000000 }
````

After investing 10MLN in the fund, second call to performCalculations returns

fund.performCalculations raw output: 
````
{ gav: 10,
  managementReward: 0,
  performanceReward: 0,
  unclaimedRewards: 0,
  rewardsShareQuantity: 0,
  nav: 10,
  sharePrice: 0 }
````

**Comment by jennazenk** [comment]
Latest change for calcGav in 0.6.2 : 
````
            gav = add(gav, mul(mul(assetHoldings, assetPrice) / (10 ** uint256(assetDecimals)), 10 ** uint256(shareDecimals)) / (10 ** uint256(assetDecimals)));   
````
https://github.com/melonproject/protocol/blob/v0.6.2-publish.2/src/Fund.sol#L508

I think it should be: 
````
            gav = add(gav, mul(mul(assetHoldings, assetPrice) / (10 ** uint256(assetDecimals)), 10 ** uint256(shareDecimals)));   
````

**Comment by retotrinkler** [comment]
what do u receive for pricefeed.getPrice(MLN_ASSET) on kovan?

**Comment by jennazenk** [comment]
I get 1 000 000 000 000 000 000 (1e18), which is correct

**Comment by jennazenk** [comment]
Why applying toWholeShareUnits at the below line ? 

https://github.com/melonproject/protocol/blob/v0.6.2-publish.2/src/Fund.sol#L241

Not sure if I understand whats its used here

**Comment by jennazenk** [comment]
Think we can close this one, as now issue is a bit different, see https://github.com/melonproject/protocol/issues/352
