### ISSUE TITLE
Await pricefeed updates before executeRequest too long

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#351]
Think there might be a mistake here: https://github.com/melonproject/protocol/blob/v0.6.2-publish.2/src/Fund.sol#L229

Unless it has changed, the idea was to wait for 2 pricefeed updates (ie 1 interval), not 2 pricefeed intervals right?  

Here it seems like it requires to wait for 2 * Interval (ie. 2 * 120s), which is quite a long time for a user. Maybe the multiplication by 2 is not necessary (?)

**Comment by travs** [comment]
Think you are correct, fixing now.

**Comment by jennazenk** [comment]
solved in https://github.com/melonproject/protocol/commit/f11835388ec86d77424cd477fbe70fed940474f4
