### ISSUE TITLE
Duplicate ranking code

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#353]
There are two ranking contracts: https://github.com/melonproject/protocol/blob/v0.6.2-deploy.9/src/FundRanking.sol
And: https://github.com/melonproject/protocol/blob/v0.6.2-deploy.9/src/Ranking.sol

One could possibly be removed.

**Comment by retotrinkler** [comment]
FundRanking looks right except https://github.com/melonproject/protocol/blob/v0.6.2-deploy.9/src/FundRanking.sol#L1 should be pragma solidity ^0.4.19;
