### ISSUE TITLE
Request for assets addition

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#360]
Here are tokens requests from users I gathered : 

- REQ
- FUN
- SAN
- MANA 
- TETHER

**Comment by fabtho** [comment]
TETHER hihi/lol. Use Dai! Sorry, just watching!

**Comment by jennazenk** [comment]
Agree I would personally be in favor of Dai @fabtho !

**Comment by jennazenk** [comment]
from my side, I was thinking we might want to add : 
- DAI
- ZRX 
- ZCASH (I mean ERC20 wrapper for zcash)

**Comment by ddkothar** [comment]
Wait you can wrap other tokens, like ZCASH. so can you also wrap BTC and other non ERC20 tokens?

**Comment by jennazenk** [comment]
Btc is already there. And yes in theory we can wrap anything because it's the testnet. On the main net it will only be possible to have existing ERC20 (until Polkadot integration).
