### ISSUE TITLE
Fund name uniqueness bug

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#361]
Fund name uniqueness doesn't seem to be enforced 

<img width="898" alt="capture d ecran 2018-01-25 a 12 05 03" src="https://user-images.githubusercontent.com/17808182/35385276-125bc050-01c8-11e8-9aad-d120c87fb84e.png">

**Comment by travs** [comment]
Added a test for this in 1979376 which passes.
Also tried to register a Fund with a duplicate name in the competiton deployment and it was rejected, so it seems to be working there at least.

What version of the protocol is being used in the screenshot?

**Comment by schmidsi** [comment]
The rejection in the competition comes from the front-end. I added a stricter test there.

I have the feeling that it happens with funds with spaces in the name. Add a test for this? Maybe exactly "Sample Test".

**Comment by travs** [comment]
@schmidsi Ok gotcha. So you can still create funds with the same name without going through the front-end?
Tried with that exact name in the test it still passes on my end.

@jennazenk What version is being used in the screenshot? Is it the current one?

**Comment by GauthamN** [comment]
We no longer enforce fund name unique check on protocol level. Can we close this issue?

**Comment by schmidsi** [comment]
@GauthamN if not, then yes.
