### ISSUE TITLE
FundRanking contract issue

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#365]
FundRanking contract returns dumb data when I call: 

`rankingContract.instance.getAddressAndSharePriceOfFunds.call()`

I use the FundRanking contract from: `@melonproject/protocol/out/FundRanking.abi.json`
With deployed address on Kovan: `0x588E2E280Da4e6CE7aB90594795FEBbedEc9D2b0`

It seems like it is aware of the number of existing funds on the version, but doesn't return the data for those funds and just populate w default data. 

Here is the raw response: 

<img width="705" alt="capture d ecran 2018-01-26 a 11 36 04" src="https://user-images.githubusercontent.com/17808182/35436047-3a500ac4-028d-11e8-8783-4c9359c5564d.png">

**Comment by travs** [comment]
Fixed by 60a39a2
