### ISSUE TITLE
Live OasisDex exchange integration

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#366]
Right now we may use a different implementation of OasisDex than what is deployed live by Maker.
If we want to integrate with their live implementation we will need to test against the exact contract that is currently deployed.

**Comment by retotrinkler** [comment]
also think they whitelist asset pairs, i.e. only if whitelisted can they be traded; just mentioning as potential error source

**Comment by travs** [comment]
Pairs that are whitelisted on mainnet deployed OasisDex (using tokens we allow as well):

```
WETH/DAI
WETH/MKR
WETH/MLN
DAI/MKR
```

**Comment by retotrinkler** [comment]
this works on livenet :)
