### ISSUE TITLE
Fund.getLastOrderId returns 'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#367]
See: 
https://github.com/melonproject/protocol/blob/master/src/Fund.sol#L758

If orders is 0, orders.length - 1 will resolve to 'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'. Not sure if this is intended or an error? Because in melon.js, this will resolve to 1.157920892373162e+77.

**Comment by travs** [comment]
Yes, it is wrapping around the minimum of the `uint` type.
This can be caught on our end by checking if `orders.length == 0`.

**Comment by travs** [comment]
I'm fine with using the convention of `fff...` meaning no orders yet if that works for you.
We could also just remove `getLastOrderId` altogether, and let users get the length of the array directly and subtract 1, but not sure about this.

**Comment by schmidsi** [comment]
I'm fine with it too. Already created a function for this: https://github.com/melonproject/melon.js/blob/7ee40748d8bf252e1b466efec522607195dabf7d/lib/utils/generic/isValidId.js

Just wanted to verify if this behavior is intended.
