### ISSUE TITLE
Remove hardcoded static array size in favour of dynamic array

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#37]
*This issue is contingent on merge of subscribe-redeem branch in its current form*

Had to use a bit of a hack in order to return an array from an external contract call [here](https://github.com/melonproject/protocol/commit/00af85c9bf2d6d1a6c00c83958a967af47cce38c?diff=unified#diff-c29a373d5ba35ade4b1045a6318cfbe9R163).

[Apparently](https://github.com/ethereum/solidity/issues/2253) we [cannot](https://github.com/ethereum/solidity/issues/166) yet [return](https://github.com/ethereum/solidity/issues/164#issuecomment-149846605) a dynamic array from an external function call in solidity yet, so the current workaround is to just make a very large (mostly empty) static array.
 
We should not have more than 200 assets in a portfolio for a long long time, so this artificial limit will work for the time being, but should be removed as soon as possible.

There may also be another approach to the problem I haven't thought about. Maybe we can use mappings instead of returning array at all?

**Comment by retotrinkler** [comment]
@travs do u know if there's any update on this as we now (w Dapp) can use latest solc version?

**Comment by travs** [comment]
Based on [these comments](https://github.com/ethereum/solidity/issues/2708#issuecomment-320957367) it should be safe to say that we will be able to do this going forward, especially with the newer versions of solidity post-metropolis, so we can close this one if you want
