### ISSUE TITLE
Restrict live version to 4 token, more information about token in tokenInfo.js file

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#374]
we should restrict live version to 4 tokens: **MLN, MKR, DAI, W-ETH**

where in token info file we store information about 
- does approve need to be set to zero
- does it have a transfer(..) w 4 parameters; On frontend this means to use transfer it with and empty input parameter due to parity.js
- does it have a tokenFallback

this is useful for melon.js; liquidity-prov; ipfs-frontend

**Comment by schmidsi** [comment]
Best would be to expose tokenInfo.js in npm build. Possible?

**Comment by travs** [comment]
@schmidsi Good idea; will include in next release.

**Comment by travs** [comment]
fixed from d930ca9 onward
