### ISSUE TITLE
Split Vault.sol into several files

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#38]
Vault.sol is getting really big, and may have functionality that could be kicked out into other solidity files.
We can probably make at least 2 files out of it if we wanted.
Lower priority than adding functionality/bugfixes.

**Comment by retotrinkler** [comment]
do u mean for legibility reason or for gas limit reasons?
if gas limit we might need to use [libraries](http://solidity.readthedocs.io/en/develop/contracts.html#libraries)

**Comment by travs** [comment]
I meant for legibility, but gas is another thing to consider if the number of assets gets large as well
