### ISSUE TITLE
Add EtherDelta and 0x exchange adapters

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#381]
https://easytrade.io/buy/EOS they have EtherDelta and 0x wrappers on contract level https://etherscan.io/address/0x9ae4ed3bf7a3a529afbc126b4541c0d636d455f6#code.
could be useful for use in terms of exchangeAdapters

**Comment by retotrinkler** [comment]
be mindful of https://github.com/melonproject/protocol/issues/330

**Comment by GauthamN** [comment]
Isn't this done?
