### ISSUE TITLE
Unexpected behaviour for redeemAllOwnedAssets

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#387]
Fund w W-ETH and MLN in it fails execute redeemAllOwnedAssets but emergencyRedeem(MLN) succeeds. The problem now is that the shares are annihilated and the W-ETH is stuck, so I have to set up another fund and get ETH etc before being able to try this again with just redeeming W-ETH

**Comment by travs** [comment]
Have confirmed this occurs for `emergencyRedeem(MLN, WETH)` on the devchain as well

**Comment by travs** [comment]
Fixed in 51d00fd
