### ISSUE TITLE
Malicious Fund Manager Can Block All Share Redemption via emergencyRedeem

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#390]
## Impact
A malicious fund manager can prevent an investor from closing their position in a fund.

## Details
For only the cost of the associated Ethereum transaction fees, a malicious fund investor can move
all assets under management to an exchange by placing open buy orders for all assets under
management. They can list these assets higher than their market value to ensure the funds will
either remain in custody of the exchange, or the manager will profit from any asset sales. A
manager can do this for any subset of assets under management. Because funds are held in
custody of the exchange, any investor attempting to perform an `emergencyRedeem` will be
unable to retrieve assets they are owed, because the funds are held in custody of the exchange
and cannot be transferred. Thus, an attacker can disable redemption and perform token listings
as necessary to prevent an investor from redeeming their shares in a fund.

Additionally, a malicious fund manager can view broadcasted `emergencyRedeem`
transactions as they enter the Ethereum network pool of unconfirmed transactions. The manager
can publish a single `makeOrder` transaction for one of the assets being redeemed, and they
can immediately broadcast this transaction with a higher gas price than the
`emergencyRedeem` transaction. If the malicious manager's transaction is executed before the
`emergencyRedeem`, the manager will be able to selectively block execution of
`emergencyRedeems`.

Moreover, this condition may arise without any malicious parties or actions. A manager may be
incentivized to sell their entire quantity of a single asset under management. In the event that a
manager makes a non-malicious `makeOrder` for a sufficiently large percentage of the fund's quantity of some asset under management, `emergencyRedeem`s involving that asset for the
fund will fail.

To summarize, there is an inherent tradeoff present in the current version of the Fund
implementation: fund managers must be able to make large orders, but large orders cause assets
to be transferred to the custody of an exchange, preventing `emergencyRedeem`s. If a fund
cannot gracefully handle `emergencyRedeem`s with large, open `makeOrder`s, this
condition can be abused by a malicious investor. For example, if a fund shuts down in the event of
an `emergencyRedeem` with insufficient funds in a contract, a malicious investor can perform
an `emergencyRedeem` for a portion of their shares to force a contract to shut down.

Line 696, in `emergencyRedeem`, attempts to transfer funds from the contract itself by calling
`AssetInterface.transfer`. However, the calculation for `assetHoldings` includes
`quantityHeldInCustodyOfExchange`

## Recommendation

Gracefully handle `emergencyRedeems` in the presence of large `makeOrders`. For
example, allow the `emergencyRedeem` function to cancel an open `makeOrder` when an
asset is requested in an `emergencyRedeem` then re-make the order based on the remaining
balance of that asset in proportion to the original list price. Due to gas limits, this scheme or other
schemes may require reducing the maximum number of assets owned by a fund or may require a
multi-transaction execution flow.

If `emergencyRedeems` cannot always be handled gracefully, for example by reverting the
transaction or by shutting down the fund, ensure investors and/or fund managers are fully
informed of any risks that impact share redemption and/or the placement of large
`makeOrders`.

**Comment by retotrinkler** [comment]
at least in latest version this should be fixed by fund being shutdown in such a case https://github.com/melonproject/protocol/blob/before-live/src/Fund.sol#L698

once shutdown any order can be cancelled by anyone https://github.com/melonproject/protocol/blob/before-live/src/Fund.sol#L455

**Comment by retotrinkler** [comment]
closing this as not an issue anymore
