### ISSUE TITLE
DOS of Fund Manager Sale via Emergency Redeem

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#391]
## Impact
An malicious investor can prevent a manager from making an order that sells a large percentage
of their holdings in an asset.

## Details
In Fund.sol, depending on the amount of an asset being sold, an attacker can wait for a fund
manager to publish a makeOrder transaction and perform an attack by publishing an
emergencyRedeem with a higher gas price than the makeOrder publication. Because the gas
price of emergencyRedeem is higher than makeOrder, this increases the probability of
emergencyRedeem being executed first. If emergencyRedeem is executed first, it will cause a
portion of the asset held by the fund to be transferred to the investor, lowering the amount of
that asset held by the fund. As a result, the sell quantity in the makeOrder may no longer be
valid, and the when the exchange attempts to transfer assets from the fund, the transaction will
fail because the sell quantity is no longer valid.

## Recommendation
When making an order, ensure the client performs a pre-flight check by querying the fund to
ensure the fund has sufficient assets to make the order.

On the contract side, if the amount of the sellAsset on hand in a fund is less than the amount in
the order, normalize the buy and sell quantities to match the amount of assets on hand to ensure
the request succeeds, even if there was an emergencyRedeem between the preflight check and
the processing of the order making.

cc: @schmidsi - The first line under recommendations may apply to melon.js (though you may already perform this check)

**Comment by jennazenk** [comment]
We indeed do this check on melon.js : https://github.com/melonproject/melon.js/blob/master/lib/fund/transactions/makeOrder.js#L30-L37

**Comment by retotrinkler** [comment]
@jennazenk does this preflight check include pending transactions?

**Comment by retotrinkler** [comment]
don't think it's huge issue though as attacker needs to pay for this attack plus with fix as in https://github.com/melonproject/protocol/issues/390 this attack would lead to fund being shutdown!

Its a one time attack that likely wouldn't give attacker financial benefits - but certainly it would lead to an unpleasant fund mgmt experience

**Comment by jennazenk** [comment]
> @jennazenk does this preflight check include pending transactions?

I don't think so as this call gets the balance of the fund at current block. will check this out!

**Comment by retotrinkler** [comment]
don't think that this is an actual issue as such an attack would only be temporary and very expensive
