### ISSUE TITLE
Subscription Execution Does Not Check Type of requestAsset in executeRequest

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#395]
## Impact
An investor subscribing to a fund using the NATIVE_ASSET can cause undetermined behavior in a
fund.

## Details
When handling a subscription request in executeRequest, the ownedAssets and
isInAssetList arrays are always modified to include the REFERENCE_ASSET for a fund.
However, the request asset bay be the NATIVE_ASSET instead. Thus when an investor
subscribes to a fund with isNativeAsset set to true, the request asset transferred from the
participant will be the NATIVE_ASSET.
Lines 256 and 257 of Fund.sol always use REFERENCE_ASSET, and the type of requestAsset
(transferred on line 260) is not checked.

## Recommendation
Check the type of the requestAsset during subscription request execution, and use the
determined type when modifying ownedAssets and isInAssetList.

**Comment by GauthamN** [comment]
In the latest version, i think it's not an issue because we force reference asset and native asset to always been in those lists

**Comment by travs** [comment]
@GauthamN Yeah, think this solves it
