### ISSUE TITLE
Centralized Exchange Adapter Poses Inherent Risk to Investors

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#396]
*Copied from document*

In a fund utilizing a centralized exchange adapter, all fund assets to be used in trading efforts are
transferred directly to the fund manager. This is expected behavior, as the manager is expected to use
those funds to make appropriate orders on an exchange. However, there is no existing mechanism that
prevents a manager from using this adapter to create large orders, and to transfer arbitrary fund assets
to the manager at any time. Essentially, there is no existing security control preventing a manager from
maliciously draining a fund, for any fund utilizing a centralized exchange adapter. Regardless of risk
management procedures implemented, this behavior will always present an inherent functional risk to
investors that is only offset through trust mechanisms.

Additionally, the process for cancelling orders requires the sender of a `cancelOrder` transaction to
return assets to the fund. If a fund is shut down and a third-party calls `cancelOrder`, that third partyi
(and not the fund manager) will have to transfer assets to the fund in order to ensure the order is
cancelled. Thus, there is no guarantee that orders can be cancelled when a fund using a centralized
exchange adapter is shut down.

Ensure investors are informed when a fund is utilizing a centralized exchange adapter or any non-
standard exchange adapter. Inform customers of the inherent risks present when this style of adapter is
used. Continue development of more nuanced risk management modules that account for these
inherent risks (e.g. limiting the size or percentage of funds to be used in open orders at any given time).

**Comment by GauthamN** [comment]
Can we close this as we are aware of the risk and will be working on the lines of the above suggestions?

**Comment by travs** [comment]
@GauthamN Yes, sounds good.
May relate back to #401 as well
