### ISSUE TITLE
Relationship Between Melonport AG and Fund Investors is Not Well Defined

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#397]
*From document*

When a fund manager creates a fund via the Version contract, that manager must generate an ECDSA
signature over the IPFS hash of a terms and conditions document. This document explicitly defines the
relationship between Melonport AG and a manager, and includes a number of clauses relating to liability
and indemnification. However, no such relationship is defined between fund investors and Melonport
AG. This lack of definition poses risks to Melonport AG in the event an investor makes claims against Melonport AG for damages or liability.

Ensure this relationship is well-defined, and implement any legal or soft controls as necessary so that
Melonport AG is accounting for associated risks.

---

One mitigation strategy for this could be to require signing of a T&C hash for investors trying to invest in a fund.
There are maybe better solutions to this, it's just what came to mind first.

**Comment by retotrinkler** [comment]
> One mitigation strategy for this could be to require signing of a T&C hash for investors trying to invest in a fund.

yeah thought the same!

guess this would need to be included in `requestInvestment` / `requestRedemption`

**Comment by retotrinkler** [comment]
doc is being worked on
