### ISSUE TITLE
Test whether repeatedly subscribing and redeeming leads causes unexpected behaviour

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#398]
*From document*

An investor can subscribe to a fund using an asset such as MLN-T, but use the emergencyRedeem
function to redeem with a broad range of assets. The properties of this behavior must be explored
further. In particular, the implications of repeatedly investing with large amounts of MLN-T (or some
other reference asset) and redeeming in a slice of the fund, in order to increase the proportion of MLN-T
in the fund, must be modelled.

As stated previously, risks related to investing with large amounts of a reference asset (such as MLN-T)
and withdrawing in a slice of a fund using emergencyRedeem have not been fully explored and
modelled.

Investigate and model fund behavior when an investor repeatedly invests in a fund with a reference
asset and withdraws in a slice of a fund. Model the impact of this behavior on share price and value of
assets owned by the fund and the malicious investor. Model the costs of any attacks and implement
controls as necessary to mitigate any risks

**Comment by jennazenk** [comment]
One mitigation to this is that a fund manager can at any times disable susbcriptions right?

**Comment by travs** [comment]
@jennazenk correct

**Comment by travs** [comment]
We no longer have `emergencyRedeem` but we can still test this and look at whether/how it affects accounting

**Comment by SeanJCasey** [comment]
Moved to CH
