### ISSUE TITLE
Existing Unit and Integration Test Suite Lacks Emphasis on Validating Security Controls

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#399]
During review of the existing unit and integration tests, consultants noticed a general lack of test cases
intended to validate routine security controls. The majority of existing test cases assert that basic fund
operations perform as designed when an expected series of events is performed.

## Recommendation
Defining and enumerating the security control mechanisms for each existing contract and any newly developed contracts. For each outlined control, develop test cases as
necessary to validate all conditional paths to assert the control functions as expected.

**Comment by retotrinkler** [comment]
Started defining and enumerating here https://hackmd.io/BzCGGYCYEYAYDYC00Am5qICwQKyIEbCySICcAZpKPKfjqMDpEA==

**Comment by retotrinkler** [comment]
^^^ this will also be great pt to use Oyente, to more rigorously verify our invariants @luongnt95 (we need approx 3 weeks to have this doc)
