### ISSUE TITLE
Address of canonical price feed as a proxy contract controlled by governance

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#405]
### Description

In form of Proxy contract (@GauthamN example)
Canonical price feed is no longer a Fund Manager setupFund input paramter but set by the technical council controlled by governance https://github.com/melonproject/protocol/blob/before-live/src/version/Version.sol#L21

### Example

Somewhat similar to https://github.com/melonproject/protocol/blob/before-live/src/version/Version.sol#L16 but w added requirements as in description

**Comment by retotrinkler** [comment]
to keep gas costs low canoncial price feed address could also be directly linked to version (hardcoded)
and given as an input parameter in fund contract creation in the version.setupFund function
in case the canonical price feed address changes governance would shutdown the version and create a new one.

it's not to be expected that canonical price feed address would change much

canonical price feed can be seen as a core component, i.e. it would change w about with the frequency the fund contract changes

**Comment by GauthamN** [comment]
Closed as decided to go with above option
