### ISSUE TITLE
Open order data is not updated when corresponding exchange order is filled

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#408]
1. Fund makes an order with `makeOrder`
2. Some other party takes full order on the exchange
3. `Fund.orders[id]` is still "open" and no data has changed

One way to deal with this is to just have our mapping of fund order IDs to exchange order IDs, and query the exchange itself to see whether the order is open, how much of the order is taken, etc, rather than storing the data in a struct and modifying it ourselves.

@jennazenk found this one today.

**Comment by retotrinkler** [comment]
Fund.orders array should be updated here https://github.com/melonproject/protocol/blob/master/src/Fund.sol#L730

^^^ this can be seen as the callback of the makeOrder

**Comment by travs** [comment]
We went with the idea of removing the `orders` array entirely, which was patched here: 33952337ff48780b302dbb5d73c0ac2a28de0212
