### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#41]
Travis' comment https://github.com/melonproject/satellite/issues/15

**Comment by retotrinkler** [comment]
@travs do you have any format/way of hosting changelog etc u prefer?

**Comment by travs** [comment]
[This works well](http://keepachangelog.com/en/1.0.0/)

Can just keep it in each repo as `CHANGELOG.md`

**Comment by retotrinkler** [comment]
awesome
