### ISSUE TITLE
Open up invest and redeem options to any tokens

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#416]
It would be great to give users the ability to invest and redeem in a Fund using *any* allowed token.
An allowed token here means one for which prices are delivered by the canonical pricefeed (#413).

**Comment by GauthamN** [comment]
Duplicate of #406?

**Comment by retotrinkler** [comment]
yeah @GauthamN to large degree duplicate of #406

**Comment by travs** [comment]
Ah yes, it totally is. Closing now
