### ISSUE TITLE
 Redundant code

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#477]
There are many instances of redundant code, usually where a condition is checked using a `pre_cond`  modifier and then further checked in the body of the code. Whilst this doesn't cause functional issues, it increases the gas cost of transactions, making the overall protocol more expensive to use. Additionally, the sanity checks in Shares are made redundant by using DSMath which already checks for overflow.

**Comment by travs** [comment]
We decided we would do this one after the competition as well, since there is no harm that can come from it

**Comment by travs** [comment]
Outdated since refactor
