### ISSUE TITLE
Small changes in synax or unused variables

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#487]
`Governance`:
- `MELON_ASSET` not needed
- `authorities[]` not needed
- `versionToProposalIds` not used
- `versionIdToShutdownIds` not used

`CanonicalPriceFeed`:
- `INTERVAL` seems not to be used
- maybe change `ofGovernance` parameter to be `ofOwner`, since owner of feed may not always be governance contract

`Competition`:
- `MELON_BASE_UNIT` not needed any more
- `bonusRate` not needed any more
- `prizeMoneyAsset` not needed any more
- `prizeMoneyQuantity` not needed any more
- `getTimeTillEnd` not needed any more

`Version`:
- does not need `owned` dependency
- consider(!) removing `VersionInterface` altogether

**Comment by jennazenk** [comment]
i think we might use getTimeTillEnd (not 100% sure) - so would be good to check in melon.js that none of these are used

**Comment by travs** [comment]
Sounds good; we will double-check all these, just noting for now

**Comment by travs** [comment]
Closing as outdated
