### ISSUE TITLE
Environmental setting for foundation, kovan, stagin etc deployments

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#49]
Currently, our dev-env and stage.melonport.com all point to the same smart contracts.

But there should be two:
- The current live one
- The current stage/dev

To differentiate between stage and live, add `-stage` to the version like specified in http://semver.org/#spec-item-9

**Comment by retotrinkler** [comment]
using truffle w `network === staging` option eg similar to here https://github.com/melonproject/protocol/blob/master/migrations/2_deploy_contracts.js#L31

**Comment by retotrinkler** [comment]
closed for reasons of similarity w other issue
