### ISSUE TITLE
Proposal to flatten contracts folder structure

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#561]
We have now a quite deep & nested folder structure in the contracts folder with no clear (or at least not for me) organisation.

So I propose a new layout:

From:
```
src/contracts/
├── dependencies
│   └── token
├── engine
├── exchanges
│   ├── thirdparty
│   ├── 0x
│   │   ├── ethfinex
│   │   ├── kyber
│   │   └── oasisdex
├── factory
├── fund
│   ├── accounting
│   ├── compliance
│   ├── fees
│   ├── hub
│   ├── participation
│   ├── policies
│   ├── risk-management
│   ├── shares
│   ├── trading
│   └── vault
├── prices
├── testing
└── version
```
To:
```
├── dependencies
│   ├── token
|   ├── dapphub
│   ├── 0x
│   ├── ethfinex
│   ├── kyber
│   └── oasisdex
├── engine
├── factory
├── accounting
├── fees
├── hub
├── participation
├── policies
├── shares
├── trading
├── vault
├── prices
├── testing
└── version
```

Explanation:
- All thirdparty code / dependencies are isolated in the `dependencies` folder. Especially the code for external exchanges should be moved there.
- The former `exchanges` folder gets merged with the `trading` folder. Exchange adapters can be seen as a utility for the trading functionality.
- `compliance` and `risk-management` is merged into `policies`
- `fund` is flattened out. The folder structure does not need to represent the dependency structure. If so, everything should be a subfolder of `version`, then `factory` and so on.

Thoughts?

**Comment by GauthamN** [comment]
I agree with first point

**Comment by travs** [comment]
would classify this as lower priority but yeah most of it sounds good.
would keep `fund/` since it's pretty plain that it holds fund components, not sure what you mean about dependency structure since it's not like that now

**Comment by schmidsi** [comment]
Sure, low prio.

Regarding `fund/`. I understand the intention. My thinking is: The flatter, the better.

**Comment by jennazenk** [comment]
>would keep fund/ since it's pretty plain that it holds fund components, not sure what you mean about dependency structure since it's not like that now

Agree to that. Also would keep compliance and risk management separated. Otherwise sounds good, we can do this when we are back on schedule.

**Comment by GauthamN** [comment]
Can be closed?

**Comment by travs** [comment]
@GauthamN Yes
