### ISSUE TITLE
[Re-]write tests where applicable

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#64]
@retotrinkler suggested a major re-write of the tests in this repo, adn I agree.
When we get a coverage tool working (#55) then we can know where should direct our efforts.

- [x] Add general tests for asset tokens (preminedAsset)
- [x] add tests for etherToken
- [x] add tests for pricefeed
- [x] tests for Version
- [x] tests for invest/redeem
- [x] test Vault

**Comment by retotrinkler** [comment]
couldnt agree more
