### ISSUE TITLE
Set CryptoCompare query dynamically

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#66]
Requires [string manipulation in Solidity](https://ethereum.stackexchange.com/a/1203/7328), and (most likely) using CryptoCompare-compatible identifiers in the token contracts (which we may get rid of soon anyway).

- [Code](https://github.com/melonproject/protocol/blob/d2793fb5ded2eb69c23a1d8691808ded6dde18b9/contracts/datafeeds/CryptoCompare.sol#L757)

**Comment by retotrinkler** [comment]
ah yeah not to do it dynamically is perfectly fine.
there is also [this](https://github.com/melonproject/protocol/blob/d2793fb5ded2eb69c23a1d8691808ded6dde18b9/contracts/datafeeds/CryptoCompare.sol#L849) option.
we might use a multisig as owner for first live version

**Comment by retotrinkler** [comment]
has been outsource in latest branch
cryptocompare price feed is now here https://github.com/melonproject/data-feed
