### ISSUE TITLE
Automated update of config files on new contract deployment

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#67]
Write a script to update (at minimum) the addresses in [this config](https://github.com/melonproject/protocol/blob/deploy-cc/migrations/config/token_info.js), and perhaps others, with newly-deployed addresses (available by `truffle networks` or through truffle's contract abstractions).

**Comment by schmidsi** [comment]
I liked having the respective addresses in the builded JSON files. It's easy to access them like this:

```javascript
import ExchangeJson from '@melonproject/protocol/build/contracts/Exchange.json';
exports.exchange = ExchangeJson.networks[web3.version.network].address;
```

([like here](https://github.com/melonproject/daemon/blob/8581e2e8acedeac95925189ee3fbc49064d49add/imports/melon/interface/addressList.js))

This gets automatically the right address depending on the network. I.e. testrpc, parity --chain dev, kovan or in the future homestead.

But I saw that the token contract JSONs arent in the `build/contracts` folder anymore. On purpose?

**Comment by travs** [comment]
@schmidsi 
They should be in the NPM package, but not tracked in github (due to binary artifacts), as per #36.

So you should still be able to do something like the code you wrote, unless the `build/` files were not included in the latest release (which would be a mistake).

**Comment by schmidsi** [comment]
Universe and Version has still an address in the build JSON, but assets were consolidated I think.

**Comment by retotrinkler** [comment]
closed for reasons of similarity w other issue
