### ISSUE TITLE
Emit event on price update

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#674]
In order to calculate past performance of a fund we need to know the price history of all tokens. Since all price sources have an update functionality, best would probably be to just emit all price updates as events.

So I propose to add the following event definition to `PriceSource.i.sol` and implement it in all implementations accordingly:

```solidity
event PriceUpdate(address[] token, uint[] price);
```

**Comment by schmidsi** [comment]
Wontfix or Fixed?

**Comment by jennazenk** [comment]
fixed https://github.com/melonproject/protocol/commit/8c6b09d7579bcc4a8aa16f680b13dc962e3ae888
