### ISSUE TITLE
Mid audit 

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#677]
KyberPriceFeed.sol

- [x]  146: baseDecimals is never used  (SMALL)
- [ ]  wouldn't price of QUOTE_ASSET always be 1? (EXPLAIN)
- [ ]  154: why is 10 ** quoteDecimals used instead of 10 ** some constant  (EXPLAIN)
- [ ]  145: baseDecimals is initialized but never used, likely supposed to be used on Line 154 as it seems that almost all the code assumes baseAsset price is multiplied by baseDecimals there

ManagementFee.sol

- [ ]  Math doesn't check out: let's say the fee is 100% annually, if withdrawn in two half-year phases, it ends up being 75% instead. Should likely be: (shares * (1 - (1 - rate)^(time_elapsed/year)))
- [ ]  Fee can be omitted due to rounding if called often enough, which can be done by a malicious user continuously to reduce the fee

PerformanceFee.sol

- [x]  frequency of payouts shouldn't be dependent on when it is called
- [ ]  The performance fees are counted based on difference from last average value of shares but that's quite unfair to people that bought in quite recently and didn't participate in the gains. They effectively pay performance fee on nonexistent performance.
- [ ]  manager can time the calls to catch high prices
- [ ]  58: currentSharePrice will end up allways being lower than what was used to calculate feeAmount, because calcSharePrice takes into account performance fees
- [x]  38: if totalSupply of shares is 0, why continue the calculation?
- [x]  why is INITIAL_SHARE_PRICE == 10 ** 18, shouldn't DENOMINATION_ASSET_DECIMALS from accounting contract be respected?

Participation.sol

- [x]  Unpaid performance fees when calling redeemWithConstraints are taken from PerformanceFee.feeAmount() which assumes the fees will be newly minted shares, but are used to calculate amount of shares to transfer, resulting in people overpaying

PriceTolerance.sol

- [x]  77: possible underflow
- [x]  41: formula likely incorrect

Engine.sol

- [x]  liquidEther is never decremented when ETH is sent to the MLN seller, which results breaking almost all the logic of the contract

Accounting.sol

- [ ]  179: this should probably be number of decimals of DENOMINATION_ASSET instead of _asset, Lines 97 & 161 are also likely incorrect
- [ ]  Many of the formulas contain various conversions that are rather difficult to reason about so we’re not confident they’re correct.

Ex: Accounting.sol:L80, Accounting.sol:L102, Accounting.sol:L161, AmguConsumer.sol:L21, KyberPricefeed.sol:L154

- [ ]  Additionally some of the operation orderings could result in precision loss.

We recommend add some sort of price conversion function, e.g. convertPrice(uint quantity, address asset1, address asset2), and refactor this formulas so that conversions are performed inside the PriceSourceInterface class. That would significantly clean up this code and help make sure there are not any bugs hiding there.

- [x] Risk management policies can be bypassed by the manager through Participation contract
Description
When PolicyManager is invoked in Participation most of the arguments are given as 0x0, despite the fact that investments can alter asset concentration, amount of positions, or include forbidden assets.

Participation.sol / Line 127
PolicyManager(routes.policyManager).preValidate(bytes4(sha3("executeRequestFor(address)")), [requestOwner, address(0), address(0), address(0), address(0)], [uint(0), uint(0), uint(0)], bytes32(0));

This means PolicyManager is effectively blind to risk management violations that occur in the form of an investment.

Recommendation
All actions which result in a change to the composition of the assets under management should be run through the policy manager (and extra care should be taken to make sure all relevant sigs should be configured to trigger said policies).

**Comment by travs** [comment]
> wouldn't price of QUOTE_ASSET always be 1? (EXPLAIN)

This quote asset may not always be the fund quote asset

**Comment by jennazenk** [comment]
All addressed in https://github.com/melonproject/protocol/pull/679/files
