### ISSUE TITLE
Mid audit 2 

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#682]
- [x] Price conversion function in kyber pricefeed 

- [x] Error in application of risk management in KyberAdapter OR ZeroExAdapter

- [x] RM / Participation : add postValidate for participation
 
- [x] requestInvestment: lock investment 

- [ ] kyber pricefeed: possibility to medianize last x prices as a protection to eventual kyber flash crashes

> Fee can be omitted due to rounding if called often enough, which can be done by a malicious user continuously to reduce the fee

- [ ] Adam proposes a fix using the lastPayout : only increment the time by the time that corresponds to the amount of shares that have been paid out

- [x] management fee : simulate with Adam's formula and consider

**Comment by travs** [comment]
Closed in #679
