### ISSUE TITLE
Investment requests can be accidentally overwritten

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#705]
Description
In Participation contract, because there is no check for existence of past request from the same sender address in requestInvestment function, existing request can be accidentally overwritten leading to a loss of funds.

Recommendation
Ideally, the contract would support multiple requests per sender address, but at the very least, a check preventing the creation of a new request from a sender address with an already pending request should be added so that.

**Comment by travs** [comment]
Fixed in #708
