### ISSUE TITLE
Add test coverage tool for our contracts

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#735]

**Comment by travs** [comment]
The two tools I'm aware of are https://github.com/sc-forks/solidity-coverage and https://sol-coverage.com/ (looks like that site is down right now though). The project is over here in the 0x monorepo anyway: https://github.com/0xProject/0x-monorepo/tree/development/packages/sol-coverage

**Comment by SeanJCasey** [comment]
Moved to CH
