### ISSUE TITLE
Investigate tokens without Kyber price (Mainnet)

### ISSUE THREAD

**Issue by schmidsi** [melonproject/protocol#758]
The following tokens seem to not have a price on Kyber:

ANT, DGD, GNO, JNT, NMR

Shall we just remove them? Or do we have the wrong address in our deployment?

<img width="280" alt="screen shot 2019-02-12 at 17 12 21" src="https://user-images.githubusercontent.com/103280/52649889-782d4080-2ee9-11e9-9ddc-57158570bfd4.png">

**Comment by jennazenk** [comment]
Yes they will be removed on next deployment

**Comment by jennazenk** [comment]
removed from registry and token files - should be ok on next deployment and even on the current one now (might need a release for the frontend @schmidsi )
