### ISSUE TITLE
Change subscribe/redeem function to payout in MLN

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#76]
Function name of `redeemInReferenceAsset` would change to `redeemInMelon`, or similar.

**Comment by retotrinkler** [comment]
- [ ] would call it `redeemUsingMelon`
- [ ] and same for `subscribeUsingMelon`
- [ ] implement option for Manager to refuse/stop any additional subscribtions/redeemals using MLN; option to redeem using slices should remain open at any time
