### ISSUE TITLE
Governance: Ability to decommission entire Versions

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#77]
https://github.com/melonproject/protocol/blob/master/contracts/governance/Governance.sol#L37

we can make this simple: doesn't even need to be multisig initially (mutlisig would require some testing for contract to contract calls)

could just be one account that controlls this - if we have time we can implement and test multisig solution

**Comment by retotrinkler** [comment]
too early

**Comment by GauthamN** [comment]
7479b094bd418a21e5a576cddd2b8322367d97f0
