### ISSUE TITLE
Ledger Settings

### ISSUE THREAD

**Issue by lukue** [melonproject/protocol#783]
on the latest version of the Ledger software (1.5.5; MCU 1.7), is a new option. In Ethereum App -> Settings is "Display Data". You need to switch it off ("NO") in order to interact with the Melon Interface via Frame.

Otherwise setting up a fund, will not work.

Would be great, if that would be written anywhere. I crashed into the issue, when actually creating the first contract.

**Comment by jennazenk** [comment]
thanks - we can add this to a tutorial
