### ISSUE TITLE
Execute request is failing

### ISSUE THREAD

**Issue by lukue** [melonproject/protocol#786]
One day ago i was investing MLN in my own fund. Today i have the option to "execute request". Unfortunately i get this error: 

<img width="1023" alt="Bildschirmfoto 2019-04-28 um 14 56 52" src="https://user-images.githubusercontent.com/46395417/56864746-4e52c880-69c6-11e9-9b2d-b8faea7449b1.png">

What is the problem here?

**Comment by jennazenk** [comment]
This is an issue for the melon-lab repo https://github.com/melonproject/melon-lab
