### ISSUE TITLE
Call for Community

### ISSUE THREAD

**Issue by iemwill** [melonproject/protocol#792]
As i realized by working myself into the protocol since few weeks, there is no active Community-channel to discuss different issues or topics. BUT there are several companies and individuals looking into this technology so there SHOULD BE AT LEAST ONE ACTIVE COMMUNITY CHANNEL!

So i will try to bundle all active working members of the protocol. These are the currently existing Channels i found:

- Github ( https://github.com/melonproject )
- Gitter ( https://gitter.im/melonproject ) 
- Telegram ( https://t.me/melonport )
- Slack? 

So if there are some other active developers/users ec. of the Melonprotocol, would you like to see one main Channel to communicate and if so, which one?

LETS GROW

**Comment by Colt21** [comment]
There is a discord-channel as well. https://discord.gg/USe9xDv

**Comment by iemwill** [comment]
Guess this one should be  closed after this article release: https://medium.com/melonprotocol/melon-council-q2-2019-update-planning-how-to-get-involved-going-forward-7d11967d0210
