### ISSUE TITLE
MLN Token migration instuction of part 2

### ISSUE THREAD

**Issue by melon2019** [melonproject/protocol#793]
Hi,
I'm too stupid to complete the migration instructions part 2.
[screenshot.pdf](https://github.com/melonproject/protocol/files/3268982/screenshot.pdf)
The transaction fails. I have tried 4 times.
When I confirm my the adress "0x3c75d37b579e0e4896f02c0122baa4de05383a6a" on my TrezorOne I noticed that the case-sensitive does not match. 
Is this the mistake? and what can I do?
Thanks Melon2019

**Comment by perhamgirl** [comment]
Hi there

Are you sure that you are entering exactly the same quantity of tokens for step2 that you did for step 1? If the quantity is more than the quantity that you approved in step 1 the process will fail.
Best regards

Melon Team

**Comment by melon2019** [comment]
Hi,
Thanks for your reply.
So can I re-do step 1 to make sure the the qty is identical? Or can I somewhere check the qty of the 1. step?
Sorry for bothering you with such questions?
Thanks!

**Comment by perhamgirl** [comment]
Do you have the tx hash of step 1?

**Comment by melon2019** [comment]
Can't check now. I'll need to check.
