### ISSUE TITLE
using callOnExchange(...) not possible

### ISSUE THREAD

**Issue by iemwill** [melonproject/protocol#794]
Hei Team!

I am trying to add an Adapter for donating to the givethDAC. Therefore i need to call a function in their BridgeContract. I planned to use callOnExchange() in Trading.sol

Here at the end of my adapter...
![image](https://user-images.githubusercontent.com/33894930/60019226-ad168480-968d-11e9-98d2-5662d31f7827.png)

But when i try to use it, i always get a compiler error, because the stack gets to deep...

![image](https://user-images.githubusercontent.com/33894930/60019118-6b85d980-968d-11e9-956d-e489a75e6466.png)

Do you know this issue or know, why its coming and how to solve this error?

**Comment by iemwill** [comment]
Is the CallOnExchange function even tested yet? Got some more problems about it...

**Comment by jennazenk** [comment]
Hello. 
`callOnExchange()`  is not supposed to be used in the Adapter, instead, it is used to call a function (delegate call) of the Adapter from the Trading contract. You would write the logic for calling the external Bridge contract in your adapter function. Please check out existing adapters so you could get an idea of usage.
You can also find more info in the docs: https://www.docs.melonport.com/chapters/exchanges.html#exchange-adapters

(and yes it is tested!)

**Comment by iemwill** [comment]
Ok, thanks for the answer. by "Trading contract" you mean the Trading.sol contract, right?

**Comment by iemwill** [comment]
As i needed to go on, i coded the functions calling the external contract into Trading.sol like this:
![grafik](https://user-images.githubusercontent.com/33894930/60499329-8ae9bb80-9cb8-11e9-80b8-1618b29caf1f.png)

Is it also ok do go that way, or should i call the external bridge as u said, from the adapter?
Furthermore i dont need or have an exchange to add, cause this module is just about donate to a given giveth DAC. So do i need to add a pseudo exchange for the use and standard of the protocol, or aint this necessary?
