### ISSUE TITLE
Trading actions don't always flow through trading contract 

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#798]
- When you make an order with 0x for example, the assets are in Trading contract post trade. 
- When you trade on Kyber, assets are directly swapped between Vault.sol and KyberProxy

The inconsistency can be confusing but more importantly if you have assets in your Trading contract, you can't trade them on Kyber before sending them back to the vault 

Not sure what we want to do yet, but instead of having takeOrder returning to the vault maybe we'd return them to trading for consistency (?)

**Comment by travs** [comment]
Adding that with the new uniswap adapter we also trade with assets that don't necessarily land in `Trading`.
My intuition is that it's better to keep the assets in the `Vault` whenever possible, so I don't have a problem with that part of it, but the inability to trade when they're in `Trading` is annoying.

It might make sense for assets to be transferred back implicitly when you do another trading action. I mean as a side-effect.

**Comment by travs** [comment]
Closed by merging Trading and Vault
