### ISSUE TITLE
Write script to execute pending investment requests

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#804]
Script should:

- find every pending investment request made through [this function](https://github.com/melonproject/protocol/blob/master/src/contracts/fund/participation/Participation.sol#L85)
- call [this function](https://github.com/melonproject/protocol/blob/master/src/contracts/fund/participation/Participation.sol#L155) on each pending investment request
- do this every N hours (configurable)
- collect the incentives and be able to retrieve them

**Comment by iherger** [comment]
For the first step, you can cross-check your results against the Melon subgraph, with GraphQL api located at: https://api.thegraph.com/subgraphs/name/melonproject/melon

Visible in the monitoring tool on: https://monitoring.melon.network/investors (bottom of page)

Query can be something like 
```graphql
{
  investmentRequests (where: {status: "PENDING"}) {
    fund {
      id
      name
    }
    owner {
      id
    }
    asset {
      symbol
    }
  }
}
```

**Comment by travs** [comment]
Tracking this one over here: https://github.com/melonproject/request-manager/
