### ISSUE TITLE
Write script to clean up orders

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#805]
From @iherger 

Script could (1) clear out expired orders, (2) return assets from Trading on funds where this was not completed.

Ivan made a script to gather this info already which is a great start.

**Comment by iherger** [comment]
Link to the script: https://gist.github.com/iherger/4fae3cf902c8c6b8e78f7faee76bf717

**Comment by travs** [comment]
@iherger can we call this one done now? this script was made to cancel orders recently right?

**Comment by iherger** [comment]
Yes.
