### ISSUE TITLE
Refactor tests to remove old melon.js and unnecessary libraries

### ISSUE THREAD

**Issue by SeanJCasey** [melonproject/protocol#814]
We want to keep tests that pertain to solidity code, but remove all tests that are only needed for the old Melon.js library, e.g., calls/events/transactions.

Primary tasks:
- use web3 for calls/transactions instead of melon.js functions
- replace `token-math` imports with `web3-utils` (`BN`, `toWei`, etc)
- remove TypeScript from test files and change file extension to `.js` (the `shared` variable is usually the only TS definition)

Styling suggestions:
- refactor the `shared` variable into scoped vars (e.g., `let environment, user, defaultTxOpts`)
- use `toWei` from `web3-utils` to represent long numbers, e.g., `toWei('1', 'Ether')` instead of `1000000000000000000`
- order imports alphabetically by filename, starting with external libraries
- define a `defaultTxOpts = { from: user, gas: 8000000 };` to use in all `send()`

Notes:
- keep convenient helper functions such as `getContract()`, `getTokenBySymbol()`, and deployment-related functions
- ignore deployment for now

**REFACTOR**

_Unit tests_

- [x] src/contracts/fund/accounting/unit/accounting.test.ts
- [x] src/contracts/fund/fees/unit/feeManager.test.ts
- [x] src/contracts/fund/participation/unit/investment.test.ts
- [x] src/contracts/fund/participation/unit/redemption.test.ts
- [x] src/contracts/fund/policies/risk-management/unit/assetBlacklist.test.ts
- [x] src/contracts/fund/policies/risk-management/unit/assetWhitelist.test.ts
- [x] src/contracts/fund/policies/risk-management/unit/maxConcentration.test.ts
- [x] src/contracts/fund/policies/risk-management/unit/maxPositions.test.ts
- [x] src/contracts/fund/policies/unit/mocks.test.ts
- [x] src/contracts/fund/shares/unit/shares.test.ts
- [x] src/contracts/fund/trading/unit/trading.test.ts
- [x] src/contracts/fund/trading/unit/tradingCallbacks.test.ts
- [x] src/contracts/fund/vault/unit/withdraw.test.ts

_Integration tests_

- [x] src/tests/integration/account0xTrading.test.ts
- [x] src/tests/integration/accountTrading.test.ts
- [x] src/tests/integration/amgu.test.ts
- [x] src/tests/integration/checkTrading.test.ts
- [x] src/tests/integration/fund0xTrading.test.ts
- [x] src/tests/integration/fundEthfinexTrading.test.ts
- [x] src/tests/integration/fundKyberTrading.test.ts
- [x] src/tests/integration/fundMaliciousToken.test.ts
- [x] src/tests/integration/fundQuoteAsset.test.ts
- [x] src/tests/integration/generalWalkthrough.test.ts
- [x] src/tests/integration/high-level/kyberTrading.test.ts
- [x] src/tests/integration/high-level/engineTrading.test.ts
- [x] src/tests/integration/high-level/userWhitelist.test.ts
- [x] src/tests/integration/kyberPriceFeed.test.ts
- [x] src/tests/integration/managementFee.test.ts
- [x] src/tests/integration/newFundTrading.test.ts
- [x] src/tests/integration/performanceFee.test.ts

_Transactions_

- [x] src/contracts/engine/transactions/sellAndBurnMln.test.ts
- [x] src/contracts/fund/trading/transactions/makeEthfinexOrder.test.js
- [x] src/contracts/fund/trading/transactions/cancelEthfinexOrder.test.js
- [x] src/contracts/fund/trading/transactions/makeOasisDexOrder.test.ts
- [x] src/contracts/fund/trading/transactions/take0xOrder.test.js
- [x] src/contracts/fund/trading/transactions/make0xOrder.test.js
- [x] src/contracts/fund/trading/transactions/cancel0xOrder.test.js
- [x] src/contracts/prices/transactions/update.test.ts (maybe can move somewhere else?)

** REMOVE **

- [x] src/contracts/exchanges/third-party/0x/utils/signOrder.test.js
- [x] src/contracts/prices/transactions/deployTestingPriceFeed.test.ts
- [x] src/contracts/dependencies/token/transactions/transferFrom.test.ts
- [x] src/contracts/dependencies/token/transactions/deploy.test.ts
- [x] src/contracts/dependencies/token/transactions/transfer.test.ts
- [x] src/contracts/dependencies/token/transactions/deposit.test.ts
- [x] src/contracts/dependencies/token/transactions/increaseApproval.test.ts
- [x] src/contracts/dependencies/token/events/onTransfer.test.ts
- [x] src/contracts/dependencies/token/calls/getInfo.test.ts
- [x] src/contracts/dependencies/token/calls/balanceOf.test.ts
- [x] src/contracts/factory/calls/managersToHubs.test.ts
- [x] src/utils/solidity/transactionFactory.test.ts
- [x] src/utils/solidity/deployContract.test.ts
- [x] src/utils/evm/getLatestBlock.ts
- [x] src/utils/deploy/deploySystem.test.ts
- [x] src/tests/system/playground-testing.systest.js (covered in generalWalkthrough test)
- [x] src/tests/system/playground-ethfinex.systest.js (covered in makeEthfinexOrder test)
- [x] src/tests/system/playground-monitoring-kyber.systest.ts
- [x] src/tests/system/playground-engine.systest.ts (covered by engineTrading test)
- [x] src/tests/system/playground-oasisdex.systest.ts (fund-related part tested by unit tests)
- [x] src/tests/system/trading-info-debug.systest.ts
- [x] src/tests/system/playground-mainnet.systest.ts
- [x] src/tests/system/playground-kyber.systest.js (tested in integration tests)
- [x] src/tests/system/playground-events-kyber.systest.ts
- [x] src/tests/system/playground-policies.systest.ts (refactored and built out as `fundRiskManagement.test.js`)
- [x] src/tests/system/playground-invest-multiple-assets.systest.ts (confirmed duplicate of `fundQuoteAsset.test.js`)
- [x] src/tests/system/playground-multiple-investors.systest.ts (made a new `fundMultipleParticipation.test.js` to handle these cases and others)

** REFACTOR MOCK ** (is this still relevant?)

- [ ] src/contracts/fund/accounting/unit/accounting.test.js
- [ ] src/contracts/fund/shares/unit/shares.test.js
- [ ] src/contracts/fund/fees/unit/feeManager.test.js
- [ ] src/contracts/fund/policies/unit/mocks.test.js
- [ ] src/contracts/fund/policies/risk-management/unit/maxConcentration.test.js
- [ ] src/contracts/fund/policies/risk-management/unit/assetBlacklist.test.js
- [ ] src/contracts/fund/policies/risk-management/unit/assetWhitelist.test.js
- [ ] src/contracts/fund/policies/risk-management/unit/maxPositions.test.js
- [ ] src/contracts/fund/trading/unit/tradingCallbacks.test.js
- [ ] src/contracts/fund/trading/unit/trading.test.js
- [ ] src/contracts/fund/participation/unit/redemption.test.js
- [ ] src/contracts/fund/participation/unit/investment.test.js

**Comment by travs** [comment]
We did it!
