### ISSUE TITLE
Register policies / "universal" policies

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#816]
We want to be able to source information about policies for offchain apps to consume, and there is no central place where that resides.

At the same time we want to not break the openness of being able to deploy and use your own policies as you wish.

One solution is to register policies, which sanctions them for use, but to not restrict the use of unsanctioned policies.

Two possibilities for implementation would be:

1. modifying the policies to be more like the fees, where there is only one policy per type, but parameters are stored on the policy per-fund. We would then register the policy.
2. register a policy factory that produces new, parameterized contracts per-fund

**Comment by SeanJCasey** [comment]
Moved to CH
