### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by SeanJCasey** [melonproject/protocol#819]
This issue is just for tracking ideas for where unit and integration test coverage can be improved.

**WISH LIST**:

Unit Tests:
- [ ] event emissions
- [ ] input/return values for all external/public functions

Integration Tests:
- [ ] fund trading on multiple exchanges
- [x] assert that funds wind up back in vault after a take order with each `ExchangeAdapter`

**IMPLEMENTED**:

- [x] `fundRiskManagement` - tests risk management policies in trade execution

**Comment by jennazenk** [comment]
Nice - probably first one to add would be risk policies

**Comment by travs** [comment]
Related: https://github.com/melonproject/protocol/issues/398

**Comment by SeanJCasey** [comment]
We should consider implementing this testing library: https://github.com/OpenZeppelin/openzeppelin-test-helpers

**Comment by SeanJCasey** [comment]
We should also examine / discuss how helpful the mock contracts are... if there's a typo in the main contract, but not in the mock contract, for example, then having mocks completely misses the point. Or the hardcoded function return values might not allow you to test what you should be testing. It might be better to always use a real system and fund.

**Comment by SeanJCasey** [comment]
We should test what happens when a fund has the max possible assets. Since we're looping through a fund's owned assets to perform certain actions (e.g., `getFundHoldings`, which is used by `redeem` and then iterated upon within that function), we should know if maxing out a fund ever causes such functions to fail.

**Comment by travs** [comment]
Two more cases:

- test that a 0xV{2,3} order can be partially taken when (a) the full takerFeeAmount is larger than what is held by the fund, and also when (b) the full takerAssetAmount is larger than what is held by the fund
- returnBatchToVault for assets with zero balance

**Comment by SeanJCasey** [comment]
^ For example re: the first bullet point, Third party A creates an order on 0xV2. Third party B takes half of this order. Our fund then tries to take the remainder.

For the 2nd bullet point, we won't have that function anymore.

**Comment by SeanJCasey** [comment]
I don't think we have any tests right now for checking the amount/price of ether funds receive from the Melon Engine. We should have a test for each discounted ETH threshold.

**Comment by travs** [comment]
For kyber pricefeed tests, at least:

- test boundaries of max spread
- test boundaries of max price deviation

**Comment by SeanJCasey** [comment]
Moved to CH
