### ISSUE TITLE
Consider tracking fund balances in state in Accounting ("internal accounting")

### ISSUE THREAD

**Issue by SeanJCasey** [melonproject/protocol#822]
As of now, Accounting relies on checking the actual token balances of the Vault (and amounts in active trades), rather than tracking balances in state.

It is possible for these balances to differ from the intended actions of a fund (i.e., a fund manager's trades and investor participation). For example, there could be edge cases such as where a bad actor sends tokens to a Vault to screw up fund concentration percentages or that simply cause problems for reporting.

It's not a huge issue, but it might make sense to handle accounting in state so that we can be more precise at calculating fund metrics.

**Comment by travs** [comment]
Closed by #914
