### ISSUE TITLE
Receiving 0xV3 Protocol Rewards

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#826]
From @SeanJCasey 

> Protocol Fee rewards -- The spec makes it seem like one needs to signal a staking pool to associate with to receive protocol fees? Are we going to bother worrying about getting a share of the fees for funds? https://github.com/0xProject/0x-protocol-specification/blob/3.0/staking/staking-specification.md#8-paying-the-protocol-fee

We chatted a bit about this and decided it was lower priority for us to integrate than other features of 0xV3, so just putting it here to be on the backburner for when we want to implement it.

**Comment by SeanJCasey** [comment]
Moved to CH
