### ISSUE TITLE
Separate Melon contracts from test-related contracts

### ISSUE THREAD

**Issue by SeanJCasey** [melonproject/protocol#840]
It's confusing that we have misc third-party and mock contracts that aren't actually used in Melon  mixed in with source contracts.

For example, there's no need to have full exchange contracts, the various mock fund components, or things like `MaliciousToken.sol` that are only used for testing.

We should partition them into separate subfolders within `src/` and `tests/`. For example:
- `src/contracts/dependencies/`: third party dependencies that we need for Melon to function. E.g., `src/contracts/dependencies/exchanges/zeroEx/` with the contracts and libs needed to create the `IZeroExV3.sol` interface.
- `tests/contracts/`: misc contracts that we need for our test suite. E.g., `tests/contracts/tokens/MaliciousToken.sol`

**Comment by travs** [comment]
As part of 0.5 upgrade #635
