### ISSUE TITLE
Deprecate overlapping functionality of dependency smart contracts

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#845]
Some of the "dependency" smart contracts we use (i.e. imported and often inherited code from dapphub, openzeppelin and others) has overlapping functionality.
In each case we should remove one of the contracts and just use the other.

For instance, there is little use in having both `Owned` and `DSAuth` in here.

**Comment by SeanJCasey** [comment]
I'm in favor of using OZ contracts where possible. I look to OZ contracts and contribution guidelines for best practices.
