### ISSUE TITLE
Change UpdatableFeedInterface to not use any parameters for update()

### ISSUE THREAD

**Issue by fubhy** [melonproject/protocol#855]
In order to be able to share a common interface between KyberPriceFeed / TestingPriceFeed, etc. it would be helpful to decouple the `update()` method from the price setting logic in case of the TestingPriceFeed. That way, we wouldn't have to add special cases for the different price feed contracts in the frontend. The interaction from the outside should not differ from the PoV of the frontend in my opinion. 

Instead, it would be great to adjust the TestingPriceFeed to have another method e.g. `setPrices()` which triggers an `update` after setting prices in a temporary variable on the contract for instance.

**Comment by travs** [comment]
Removed the interface so this is no longer needed
