### ISSUE TITLE
Take multiple orders from MatchingMarket in one go

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#864]
Would be nice to be able to take (potentially) many orders from OasisDex MatchingMarket in a single transaction.
Right now we take each individually, which could be bad UX if a user wants to make a large order.

We could use [this function](https://github.com/makerdao/maker-otc/blob/master/src/matching_market.sol#L337) in our adapter to achieve this.

There is another possibility to implement this by pre-signing a bunch of takes but that's not exactly the same as this, and might have other flaws (e.g. one or more tx fails and things get a bit messy).

**Comment by SeanJCasey** [comment]
Moved to CH
