### ISSUE TITLE
Consider: Dapp

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#87]
https://dapp.readthedocs.io/en/latest/
- has great extensions
- hsevm
- testing
- logging tools

**Comment by travs** [comment]
I like the simplicity of this one, and the fact that it is modular (e.g. can swap out the default testing tools eventually).

**Comment by dbrock** [comment]
It's very simple. It almost doesn't even do anything. So if you like not doing things you don't even know what they are, then this this is for you.

**Comment by retotrinkler** [comment]
there's beauty in simplicity :)

**Comment by retotrinkler** [comment]
tool looks really great - think we will explore switching as soon as feasible

**Comment by retotrinkler** [comment]
closing this to keep open issues few
