### ISSUE TITLE
canUseFundName returns true, seemingly regardless of input

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#880]
This might be a bug, or we just need to use the `canUseFundName` function on Registry with unintuitive inputs.

Fund names cannot be the same, and it is prevented at the Registry level. This works out when we try to create funds with the same name, but when we manually call `canUseFundName` it always returns `true` (at least for the inputs we have tried so far, including a previously-created fund's name as a string, as bytes, the hash of that, etc.).

CC: @iherger

**Comment by iherger** [comment]
I found the problem: you have to pass in the name of the fund as a properly formatted hex string, e.g. as `0x00000000000000000000000000000000000000000000000000000046756e6431` for the fund name `Fund1`

**Comment by travs** [comment]
@iherger 

Ok, but I still get a false positive with `MBS` on mainnet it seems.

```
# how I get the hex string
$ seth --to-word $(seth --from-ascii Fund1)       

00000000000000000000000000000000000000000000000000000046756e6431
```

And yet:
```
$ seth call 0x1Bfd21f7db126a5966d2C09492676807a68859Ba 'canUseFundName(address,string)(bool)' 0x0000000000000000000000000000000000000000 $(seth --to-word $(seth --from-ascii MBS))

true
```
