### ISSUE TITLE
Tokens for next deployment

### ISSUE THREAD

**Issue by jennazenk** [melonproject/protocol#883]
- [ ] Remove old DAI (SAI), DGX

- [ ] Add: new DAI, LINK, SNX, ANT, RLC, ENJ, ENG, REN, MANA, OMG, USDT

Complete list is 19 tokens: 
WETH 
MLN 
BAT  
DAI 
KNC 
MKR
 REP
 ZRX
USDC
WBTC 
LINK
SNX
ANT
RLC
ENJ
ENG
REN
MANA
OMG
USDT

**Comment by travs** [comment]
Merged with #858
