### ISSUE TITLE
Add security tool to our build

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#888]
[MythX](https://mythx.io/) seems like it would be easy to integrate into our pipeline, so we should give that a shot.

**Comment by SeanJCasey** [comment]
Others that we could investigate:

- [Web3j](https://blog.web3labs.com/auditing-smart-contracts-with-web3j)
- [Securify](https://medium.com/chainsecurity/release-of-securify-v2-0-6304a40034f)

**Comment by SeanJCasey** [comment]
Moved to GH
