### ISSUE TITLE
Use error codes in revert messages

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#893]
Would allow frontend to customize error message without need to change sol code. Could be as simple as something more "machine readable" like:

```
require(false, 'ERROR_NOPE');
```

@SeanJCasey mentioned [compound](https://compound.finance/developers/ctokens#ctoken-error-codes) does this.

[Example from their repo](https://github.com/compound-finance/compound-protocol/blob/bfc2914505b8d794c4136430708f746c5bda618e/contracts/Comptroller.sol#L331) and [ErrorReporter.sol](https://github.com/compound-finance/compound-protocol/blob/bfc2914505b8d794c4136430708f746c5bda618e/contracts/ErrorReporter.sol).

Also would be interesting to consider possible advantages to that approach: of communicating with error codes between functions.

- also error messages that have more detail (dynamic where possible)

**Comment by SeanJCasey** [comment]
Worth noting that (if I remember correctly) Compound doesn't return an error string through `require`, but rather lets txs succeed and returns the error code as a `uint`, with `0` meaning that there was no error.

**Comment by SeanJCasey** [comment]
Moved to CH
