### ISSUE TITLE
Handle assets sent directly to the fund

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#897]
A token holder can send their tokens directly to the fund (i.e. without investing, and without manager taking a trade). In this case, when we start using internal accounting, these assets would be frozen there.

We could handle it in really any way we want, including by not handling it.

Relevant after #822

**Comment by SeanJCasey** [comment]
Just pasting a potential solution here from out chat for future reference:

One alternative would be that when redeeming from a fund, the nav/gav are calculated based on internal accounting, but the actual payouts are calculated as a proportion of the total contract balance of each asset. If we do that, then extra assets sent to the fund could never affect the fund metrics, and they also would not be lost, in that they are eventually distributed to share holders.

**Comment by SeanJCasey** [comment]
Moved to CH
