### ISSUE TITLE
Incentive change while there is an open request leads to unexpected result

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#898]
Example scenario:

1. Registry has `10 finney` as default incentive
2. Alice calls `requestInvestment`, sending `10 finney` to the participation contract as an incentive
3. `Registry.owner` calls `setIncentive(1 eth)`
4. After this, trying to execute Alice's request either:
 a. fails if there is not enough eth in Participation, or
 b. drains more eth than expected from Participation, and potentially causes other users' requests to fail

One fix would be to attach incentive amount to the request struct in the `requestIncentive` tx

**Comment by SeanJCasey** [comment]
Moved to CH
