### ISSUE TITLE
More sophisticated MLN premium pricing function in Engine

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#899]
Right now the `premiumPercent` function in Engine is just stepwise and applies to the entire supply of eth in the contract (@SeanJCasey brought attention to this in chat a while ago).

This was a rough preliminary approach since the goal was just to be a sink, but we could come up with something that applies to the supply more dynamically, or has some other interesting property.

**Comment by SeanJCasey** [comment]
Moved to CH
