### ISSUE TITLE
Consider ERC20 extensions and other token standards

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#919]
From Adam:

Beware of extensions of ERC20 standard such as ERC223, ERC777 or ERC827 which call the destination address during transfer. If any such token is added as an asset, it activates a host of reentrancy issues.

**Comment by SeanJCasey** [comment]
We can/perhaps should consider this when this big architectural PR is ready for review, since it will change the way exchange adapters interact with account funds and balances: https://github.com/melonproject/protocol/pull/914

**Comment by travs** [comment]
this can be taken care of by having a convention within the council to only permit tokens whose standards are not changeable and have some integration/handling at the protocol level
