### ISSUE TITLE
Add buyer,seller in Trade event

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/protocol#92]
https://github.com/melonproject/protocol/blob/master/contracts/exchange/Exchange.sol#L65

Approach OasisDex re this as well

**Comment by travs** [comment]
Can we also do this in the exchange adapter; wrap the `trade` function that an exchange implementation provides and fire our event inside the wrapper.

Does that make any sense?

**Comment by retotrinkler** [comment]
@jennazenk is this also needed for decentralized-portal?

**Comment by retotrinkler** [comment]
closing this as think we mainly switch to single parameter events
