### ISSUE TITLE
Break up redeemWithConstraints with helper functions

### ISSUE THREAD

**Issue by SeanJCasey** [melonproject/protocol#923]
As the primary share redemption function, this is a critical part of the system, and it's a bit long, so would be nice to break this up into well-named helper functions imo, for visual clarity.

Not strongly opinionated though, so feel free to ignore.

**Comment by travs** [comment]
@SeanJCasey Think this one might fit with the theme of the Participation-as-infrastructure PR?

**Comment by SeanJCasey** [comment]
Resolved with #960
