### ISSUE TITLE
Switch general dependency contracts to OpenZeppelin's

### ISSUE THREAD

**Issue by SeanJCasey** [melonproject/protocol#924]
We should switch dependency libraries (IERC20, safemath, etc) over to OpenZeppelin. Will be easier to keep up with changes, and we can potentially incorporate more OZ base contracts as they are released. E.g., the new lib for using the CREATE2 opcode, `EnumerableSet`, etc: https://forum.openzeppelin.com/t/openzeppelin-contracts-v2-5/2155

**Comment by travs** [comment]
You mentioned this in our chat and it wasn't decided either way.
Certainly possible, but also need to consider switching the other way as well.

**Comment by SeanJCasey** [comment]
Moved to CH
