### ISSUE TITLE
Revoke unused asset approvals after a successful order fill

### ISSUE THREAD

**Issue by SeanJCasey** [melonproject/protocol#928]
The new `validateAndFinalizeFilledOrder` modifier introduced in #822 needs to revoke unused asset approvals (the difference between expected and actual fill amounts).

This will involve having the modifier handle all asset approvals as well. Either that, or the modifier could be split up into 2-4 functions that each exchange adapter calls, rather than one modifier.

This can be decided after the PR is merged, but before the next release.

**Comment by SeanJCasey** [comment]
Now that we're getting rid of non-instant settlement transactions, we could also just revoke all asset approvals (reset them all to `0`) afterwards. i.e., we could do away with increase/decrease allowance and just directly set amounts again. Would need to re-institute doing this with increase/decrease when we have non-instant settlement.

**Comment by travs** [comment]
This one is done over here: https://github.com/melonproject/protocol/blob/a83dee749e90a783cf20c8dd878815e3eb27b4cc/src/exchanges/libs/OrderFiller.sol#L307
