### ISSUE TITLE
Support tokens with incomplete ERC20 implementation

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#939]
Some tokens (USDT, OMG) do not properly implement ERC20 `transfer`, since they do not return a `bool`. This causes transfers within our fund to fail at some points, due to the complete ERC20 interface we use.

We can fix this by using an interface that doesn't specify a return value for `transfer`.

**Comment by jennazenk** [comment]
Just as a reminder for the future, here are the tokens we refrained from adding for this reason: USDT, OMG 

Other tokens we had to not add for other reasons: ENG, SNX 

@travs if you think of others add them here

**Comment by SeanJCasey** [comment]
Moved to CH
