### ISSUE TITLE
Batch add to AssetBlacklist / remove from AssetWhitelist 

### ISSUE THREAD

**Issue by iherger** [melonproject/protocol#943]
Currently, it is only possible to add one asset at a time to an existing AssetBlacklist, and to remove one asset at a time from an existing AssetWhitelist.

It would be quite useful to have two new methods, with which we could add several assets to an existing AssetBlacklist and remove several assets from an existing AssetBlacklist.

**Comment by SeanJCasey** [comment]
Moved to CH
