### ISSUE TITLE
Fill multiple orders across exchanges up to some desired quantity

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#951]
We could implement trading in such a way that, not only are multiple orders taken, but that failing orders (out of date, already filled, or otherwise invalid) are skipped, and other orders are moved on to.

Such a function could take a `maxFillQuantity` param, along with a (sorted*) list of orders for which execution should be attempted. The sorting should be done offchain, where the best-priced orders are put into a higher priority in the sequence.

One open question would be how best to implement the try/fail logic for each of these orders.

Related: #950 #864 #895

**Comment by SeanJCasey** [comment]
Moved to CH
