### ISSUE TITLE
Make Registry more abstract/extensible

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#958]
The general idea behind this is to allow everything to be registered in a way that is more futureproof.
If integrations boil down to a single contract and its adapter, then we could register them similar to how we register exchanges/adapters now.

Because of the possibility for large changes in architecture (e.g. we want to register a new type of thing in the future that we haven't thought of now), it might also make sense to generalize the registration to the point where we just have one `register(kind, data)` function, though that might be overkill for this issue.

Related to #816

**Comment by travs** [comment]
Related to #812

**Comment by SeanJCasey** [comment]
Moved to CH
