### ISSUE TITLE
Combine fund components

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#967]
We spoke today about an approach to combining fund components where there are ultimately 3 components. The general idea is a Shares component, a Vault component and a "Mandate" component.

- `Shares` is almost as it exists in `develop` at the time of writing, with some added accounting functionality and (most likely) some changes to do with state and fee rewarding.
- `Vault` will take the remaining functionality from `Accounting` not implemented by `Shares` above. It also remains the custody component and is controlled by the Shares component (`withdraw` for redemption), and the manager (integrations).
- `Mandate` is the combination of `FeeManager` and `PolicyManager`. There are changes needed for each of these that will be tracked in separate issues, but the general idea is that they become more lightweight (e.g. policies deployed once) and abstract (e.g. policies taking arbitrary arguments). The manager has some measure of control over the `Mandate` in that they can add policies and fees.

Completion:

- [x] #813
- [x] #889
- [ ] #968
- [ ] #969

**Comment by SeanJCasey** [comment]
Moved to CH
