### ISSUE TITLE
Integrations and their infrastructure

### ISSUE THREAD

**Issue by travs** [melonproject/protocol#971]
This groups issues to do with the new "Everything is an Integration" mindset we're taking.

Includes things like:

- integrations themselves
- making the registry more abstract when it comes to dealing with Integrations
- how Integrations are defined (i.e. Adapters and their common parent and/or interface)
- changes to Vault required to interact with arbitrary protocols via above adapters
- how Integrations interact with policies (shared with PolicyManager rework happening in parallel)
- changes to CallOnExchange necessary for all of this

Completion:

- [ ] #973
- [ ] #974
- [ ] #975
- [ ] #976

**Comment by SeanJCasey** [comment]
Moved to CH
